### ISSUE TITLE
Access kegg information from kegg API

### ISSUE THREAD

**Issue by zertan** [SysBioChalmers/RAVEN#1]
Currently, there is no direct access to updated databases for use in downloadKEGG, getGenesFromKEGG, etc.). This may be resolved by updating the functions to use the kegg rest api. Also state clearly that the current functions use older version of the databases and add the older versions back to RAVEN.

**Comment by edkerk** [comment]
The downloadKEGG function has been removed, as it wouldn't work with newer Matlab version anyway. Kegg rest api doesn't allow bulk download. If one downloads the KEGG data anyway, the existing functions can still be used to generate the required KEGG structures for Raven.
