### ISSUE TITLE
Output list type field as array of string in Yaml

### ISSUE THREAD

**Issue by Hao-Chalmers** [SysBioChalmers/RAVEN#107]
The JSON/Yaml formats appear to be very useful in GEM curation, exchange and other things, among which one application is for visualization purpose. Now Yaml has been used as input for Metabolic Atlas website development.

However, the current writeYaml function treats the 'list' type fields (e.g. eccodes,subSystems) differently. It outputs the value as string when there is only one element, but output into array of string when there are multiple elements. This inconsistence causes problems when loading the file to public Yaml parser (such as in python), because the information cannot be correctly extracted if some elements have on value and others have multiple. Now this issue has been addressed in this branch: [81be856](https://github.com/SysBioChalmers/RAVEN/commit/d856b852f94e9ae10720b782be78e28acb3622cb).

**Comment by BenjaSanchez** [comment]
@Hao-Chalmers 
1. When writing the function I followed the cobrapy standard, and they actually also have this distinction when it's only 1 field or several: see example file in issue #77, for instance reactions `r_2246` (one ec-code) and `r_2248` (2 ec-codes). So if we do what you suggest we would loose compatibility with them, however eventually we want to allow cobrapy users to contribute to our models. 
2. In our repos we should have `.yml` files as succinct as possible, so they can show the most amount of changes with the least amount of lines. This change would go against that principle.

So instead I would suggest a separate function that can convert the `.yml` to a parser-compatible version.

**Comment by edkerk** [comment]
@Hao-Chalmers 

As @BenjaSanchez said, the default `writeYaml` output should not be changed.

As alternative, include a parameter in the `writeYaml` function, e.g. `compact` or `parseable`, and set this to `true` if you want your precise format. The default for this parameter should be `false`, so the function continues to function as intended. If this parseable format requires a lot of changes, it might indeed make more sense to write a specific function for this purpose, either as part of RAVEN or as part of the relevant repository.

**Comment by Hao-Chalmers** [comment]
@BenjaSanchez, @edkerk 

Here are my comments:

1. The propsed change in this branch keeps the yml file in succinct style without introducing addtional lines, and doesn't go aginst the `compact` principle.

2. This function attemps to follow the JSON/Yaml scheme proposed by cobrapy. But any scheme should be open for adjustments toward better fit of needs, which is contineously changing. Actually cobrapy doesn't clearly specify this condition.

**Comment by BenjaSanchez** [comment]
@Hao-Chalmers it would definetively include extra lines, for instance what is now:
```
- ec-code: 1.3.3.6
```
would then be:
```
- ec-code:
  - 1.3.3.6
```

**Comment by Hao-Chalmers** [comment]
True, it does. But there won't be many though :-)

**Comment by BenjaSanchez** [comment]
@Hao-Chalmers actually they would be many new lines: the `.yml` file of yeast-GEM saved with your proposed change would be 82,202 lines, compared to 74,394 lines as it is currently stored.
And completely agree with @edkerk, we can have secondary ways of outputting the model but the way to store it in the repo should be the most compact option.

**Comment by Hao-Chalmers** [comment]
@edkerk A similar [issue](https://github.com/opencobra/cobrapy/issues/706) has been proposed in cobrapy repo for adjustment in implementation. Let's see how it proceeds.

@BenjaSanchez There won't be much differences with whether 82,202 or 74,394 lines, because both could not be managed by human eyes. But there would be no difference for digital storage.

The optional `parsable` output could be a solution, if it turned out to be optimal.
