### ISSUE TITLE
help: getKEGGModelForOrganism gives error that genes.pep cannot be found

### ISSUE THREAD

**Issue by bapimandal** [SysBioChalmers/RAVEN#110]
Hello,
I am trying to reconstruct a bacterial model using the function 'getKEGGModelForOrganism' with organism id and protein fasta sequence as input. However, I am receiving the below error:

"The file 'genes.pep' cannot be located at / and should be downloaded from the KEGG FTP"

Kindly help in resolving this error.

**edit:** solution provided in https://github.com/SysBioChalmers/RAVEN/issues/110#issuecomment-389801260

**Comment by bapimandal** [comment]
Hi @simas232 ,

Thank you for your reply. 
This time I got this error after specifying the pre-trained HMM:

The file 'genes.pep' cannot be located at prok100_kegg82/ and should be downloaded from the KEGG FTP.

Bapi.

**Comment by edkerk** [comment]
@bapimandal Can you please indicate _**exactly**_ what command you used, which RAVEN version you have installed (any of the [stabile releases](https://github.com/SysBioChalmers/RAVEN/releases)?) and on what operating system?

**Comment by bapimandal** [comment]
@edkerk ,

I am using the below command for the RAVEN 2.0.0 version on Windows 10.
model=getKEGGModelForOrganism('roa','roa.fasta','prok100_kegg82');

I am unable to resolve the error.

Bapi.

**Comment by edkerk** [comment]
With the command you specified, the HMMs should automatically be downloaded and extracted, it should not require the `genes.pep` file, as HMMs are then provided for each KEGG reaction.

Something might have gone wrong when downloading or extracting the files. E.g., if extracting the ZIP file was cancelled half-way, some of the HMMs will be missing. Please delete the `prok_kegg82` folder and ZIP file in the current working directory and try to rerun the same command.

If this does not work, you could manually download and extract the HMMs from the [Wiki](https://github.com/SysBioChalmers/RAVEN/wiki/HMMs). Ìn this case, make sure you correctly specify the directory when running the function, if this is not the current working directory. Example: if the ZIP file is extracted to ' `C:\Documents\prok100_kegg82`, then specify this as `model=getKEGGModelForOrganism('roa','roa.fasta','C:\Documents\prok100_kegg82');`

**Comment by bapimandal** [comment]
@edkerk 

You were right about the HMMs downloading issue. However, the error is something else this time:

Error using dispEM (line 50)
Error when querying HMM for K00759:

Error: Failed to open sequence file D:

Error in getKEGGModelForOrganism (line 707)
                dispEM(EM);

Bapi.

**Comment by simas232** [comment]
I see that the MATLAB cannot access `roa.fasta` file. Do you have it in the current working directory? Also make sure that the full name of your file is `roa.fasta`, not `roa.fasta.txt`.

**Comment by edkerk** [comment]
@simas232 FYI, I've included a check for this in df07ba935605d6df5e292783be46d752414e9335. As this is non-critical, this will make it slowly into devel and master.

**Comment by bapimandal** [comment]
@simas232 @edkerk , 
Thank you for your time and suggestions. I could generate the model. 

Bapi.
