### ISSUE TITLE
help: what organism ID to use for getMetaCycModelForOrganism

### ISSUE THREAD

**Issue by bapimandal** [SysBioChalmers/RAVEN#112]
Hello

I could generate the draft model using the function 'getKEGGModelforOrganism' with organism ID and protein sequence. However, I could not find the organism ID for my organism in the MetaCys to be used in the function 'getMetaCycModelForOrganism'. I would like to refine my model by combining both KEGG and MetaCys model. Kindly help.

Bapi.

**Comment by Hao-Chalmers** [comment]
The MetaCyc organism id is defined by you (yourself).

On 18 May 2018, at 08:16, bapimandal <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello

I could generate the draft model using the function 'getKEGGModelforOrganism' with organism ID and protein sequence. However, I could not find the organism ID for my organism in the MetaCys to be used in the function 'getMetaCycModelForOrganism'. I would like to refine my model by combining both KEGG and MetaCys model. Kindly help.

Bapi.

**Comment by bapimandal** [comment]
@Hao-Chalmers 
Thank you...it worked.

Bapi.
