### ISSUE TITLE
Issues error with getBlast.m

### ISSUE THREAD

**Issue by lucaz88** [SysBioChalmers/RAVEN#128]
Hi, 
I have a problem running 'getBlast.m'.
The command line I am running is:

`blastStructure = getBlast('new_model', 'new_model.faa', {'old_model'}, {'old_model.faa'});`

At line 128, when it is importing the results of the blast organism-to-model all the fields of structure array 'A' have only one row/element and I get the following error:

> BLASTing "old_model" against "new_model"..
> BLASTing "new_model" against "old_model"..
> Index in position 2 exceeds array bounds (must not exceed 1).
> 
> Error in getBlast (line 131)
>     tempStruct.toGenes=A.textdata(:,2);

I think that the scripts is failing to correctly import the temp txt file and that the reason might be the gene names of the model fasta file that are numbers and not characters. Here is an example of the first 10 lines of that blast file:

> Sm_00029441-RA,303034,1.00e-115,47.927,386,361,65.28
> Sm_00029441-RA,300894,6.23e-20,24.825,286,92.4,42.66
> Sm_00029441-RA,300885,7.26e-20,26.449,276,92.4,43.84
> Sm_00029441-RA,306441,1.02e-19,30.556,288,90.9,46.18
> Sm_00029441-RA,310017,1.68e-19,25.077,323,88.6,40.87
> Sm_00029441-RA,Phatr3_J13617,3.18e-18,26.712,292,86.3,47.60
> Sm_00029441-RA,300506,1.22e-17,26.596,282,85.9,42.20
> Sm_00029441-RA,305513,2.77e-17,23.575,386,84.7,39.64
> Sm_00029441-RA,309874,3.86e-17,27.517,298,84.0,41.61
> Sm_00029441-RA,Phatr3_EG02341,1.78e-16,28.383,303,81.6,42.24
> Sm_00029441-RA,Phatr3_EG02340,1.78e-16,28.383,303,81.6,42.24
> Sm_00029441-RA,311654,2.88e-16,25.309,324,79.3,39.81

Could this be the reason? and how can I fix this issue? I cannot change the gene names in the fasta file because they won't match with the gene names of the model.
Many thanks!!

**Comment by simas232** [comment]
@lucaz88, what about the genes in `old_model`? Are they also in the same format like in `new_model.faa`?

**Comment by lucaz88** [comment]
@simas232 I am not sure what do you mean for same format, can you make an example?
In any case I just manually edited the first line of the tmp file reported in the previous comment, from
> Sm_00029441-RA,303034,1.00e-115,47.927,386,361,65.28

to

> Sm_00029441-RA,**P**303034,1.00e-115,47.927,386,361,65.28

and not the script is running smooth!
Is there a way to fix the way that the tmp file is imported in line 128?

**Comment by simas232** [comment]
@lucaz88, I re-read your first point and got an answer. Just wanted to make sure that the genes in `old_model` and `old_model.faa` are identical.

It seems MATLAB is unable to parse BLASTP results appropriately by failing to split the lines into the columns. I suppose this could be fixed by temporarily appending the numeric genes with the letters and then removing it as soon as `blastStructure` is created. Will keep you updated regarding such implementation.

**Comment by lucaz88** [comment]
Cool! Thanks and looking forward for news!

**Comment by simas232** [comment]
@lucaz88, the bug is fixed in 63ec5a7ac6aea38b7e5166d56c6ce911d80230d7, part of fix/getBlast branch.

**Comment by lucaz88** [comment]
Many thanks! However now I am getting this new error while running the  `getModelFromHomology` function:

> newdraftModel = getModelFromHomology(templateModelList, blastStructure, 'new_model', {}, 1, false, 10^-30, 200, 40, true);
> Undefined operator '<' for input arguments of type 'table'.
> 
> Error in getModelFromHomology (line 88)
>     indexes=blastStructure(i).evalue<maxE & blastStructure(i).aligLen>=minLen & blastStructure(i).identity>=minSim; %Do it in
>     this direction to lose NaNs

**Comment by edkerk** [comment]
Pushed to `devel`, issue will be closed when pushed to `master`.

**Comment by lucaz88** [comment]
ops, sorry!
