### ISSUE TITLE
bug: fillGaps errors when using KEGG as template model

### ISSUE THREAD

**Issue by phemmy2k2** [SysBioChalmers/RAVEN#146]
### Description of the issue:
KEGG and MetaCyc models were successfully merged using combineMetaCycKEGGModels(). 
Thereafter I try to fill gaps using the full KEGG model but received the following error.

```matlab
Matrix index is out of range for deletion.

Error in removeMets (line 101)
reducedModel.metCharges(indexesToDelete)=[];

Error in simplifyModel (line 154)
reducedModel=removeMets(reducedModel,notInUse);

Error in fillGaps (line 181)
allModels=simplifyModel(allModels,false,false,false,true,false,false,false,[],true);
```
#### Reproducing this issue:
```matlab
model_MetaCyc = getMetaCycModelForOrganism('fly','GCF_000001215.4_protein.faa',true,false,false)

model_KEGG=getKEGGModelForOrganism('dme','GCF_000001215.4_protein.faa','euk100_kegg82','output',false,false,false,10^-15);
[newModel, removedRxns]=removeBadRxns(model_KEGG,1,{'H+'},true);

CombinedDraftModel=combineMetaCycKEGGModels(model_MetaCyc, newModel);

keggModel=getModelFromKEGG([],false,false,false);

[newConnected, cannotConnect, addedRxns, balancedModel, exitFlag]=fillGaps(CombinedDraftModel,keggModel,true,false,false,[],params);

```

#### System information
* Please report:
1. RAVEN version (stabile [release](https://github.com/SysBioChalmers/RAVEN/releases), `devel` branch?)
2. Operating system (Windows/Mac/Linux; include version)

**I hereby confirm that I have:**
- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)

**Comment by phemmy2k2** [comment]
Thank you @edkerk I have it running with version 2.0.1. However, I discovered that getKEGGModelForOrganism() is throwing error in the latest version. Below is the code and the error, you can try to replicate it.

>> model_KEGG=getKEGGModelForOrganism('dme',false,false,false);
Error using exist
The first input to exist must be a string scalar or character vector.

Error in getKEGGModelForOrganism (line 221)
    if ~(exist(fastaFile,'file')==2)

**Comment by edkerk** [comment]
Documentation of the functions is amended in version 2.0.2.
