### ISSUE TITLE
ravenToCobraModel.m

### ISSUE THREAD

**Issue by HenrikCordes** [SysBioChalmers/RAVEN#15]
Hi there,

could be that in line 29 
fields = rmfield(rModel,fieldnames(setdiff(fieldnames(rModel), f.optionalEquiv)));
should be
fields = rmfield(rModel,(setdiff(fieldnames(rModel), f.optionalEquiv)));
instead?

**Comment by simas232** [comment]
Hi @HenrikCordes ,

The function ravenToCobraModel.m is now fixed and should work fine. Please download the latest commit from 'devel' branch, test it and let us know about the results you got.

The obtained COBRA model structure is supposed to be compatible with the latest COBRA version.

**Comment by edkerk** [comment]
This function is now also in the master branch
