### ISSUE TITLE
Update to 1.10 from 1.08

### ISSUE THREAD

**Issue by rasmusagren** [SysBioChalmers/RAVEN#18]
Hi all,

It seems that you based the "new" RAVEN on version 1.08, but the newest version is actually 1.10. This is because I used some RAVEN functionality while I was at Novo Nordisk and I also fixed bugs if I got mails about them. Something I should probably have mentioned earlier :)

The changelog for 1.08 to 1.10 says:

-Changed in loadSheet to allow for formulas in Excel sheets
-Fixed a bug in makeSomething/consumeSomething
-Moved the code for loading and processing Excel sheets to separate functions (loadSheet and cleanSheet) in order to prevent duplicate code
-The function loadWorkbook was added, mainly for easier loading of the Apache POI library from non-RAVEN functions
-The function addJavaPaths was added to use static Java paths instead of dynamic for better robustness
-References to the Matlab functions getfield and setfield were replaced with dynamic structures
-Some additional checks regarding Mosek licence
-Fixed a bug in simplifyModel when using the group linear option
-Changed in haveFlux so that it can deal with infinite bounds
-Added some more error checks to checkSolution
-An option was added to simplifyModel to identify reversible reactions which could only carry flux in one direction and change them to irreversible
-Added support for newer versions of HMMER to getKEGGModelForOrganism
-Fixed a bug in constructEquations
-Minor bug fixes and formatting in order to reduce the number of Matlab warnings in the editor

The most valuable part here is that handling Excel I/O was largely rewritten and should work better (and on all platforms) now. If we decide to merge RAVEN with my software for fermentor modelling (MEMO) then this update is required.

I don't know how to deal with this. I've merged RAVEN 1.10 with the master branch to the best of my ability in the branch 108_to_110. For now I have not included the calls to optimizeProb() because I want to test that everything seems to work first. It should of course be done though.

What do you think about this? Is there a large difference between the master branch and the devel branch(es)?

Cheers,
Rasmus

@edkerk @simas232 @shaqHosseini @varemo

**Comment by edkerk** [comment]
This is great!

I've been submitting stuff to devel branch, not to make the master branch unstable, and then after a while merge devel to master if everything continues to work fine. The only issue between devel and 1.10 I see is changes in importModel that would need to be checked (as it also changed in '1.10').

I had a quick look at 1.10, and I suppose we should make sure we keep the changes and bugfixes, while not removing the work that we've been doing in the last year based on 1.08. So what if we stepwise move 1.10 to devel, double checking each diff that we're not removing functionalities that had been added recently?

**Comment by rasmusagren** [comment]
That's basically what I tried to do but for the master branch. I tried to be careful but the problem is that there are hundred of small changes that primary deals with "good coding practices" and/or compatibility with new Matlab versions. Maybe we could diff devel to master and then manually merge changes to 108_to_110? In retrospect I should of course merged with devel instead of master :) It would be nice to sit down and talk about what you did for the more major stuff (Cobra/solver/new KEGG/..). Do you guys have an hour or two to spare on Friday maybe?

**Comment by simas232** [comment]
The changes in RAVEN 1.10 are essential, so we obviously need to include them in the repository. I therefore agree with Ed's suggestion that we should incorporate RAVEN 1.10 changes into 'devel' branch. This will also deal with your recent commits in 'master' branch, Rasmus. We can delete '108_to_110' once the whole incorporation process is complete and go on with 'devel' branch.

So what about creating a checklist for all functions between 'devel' and '108_to_110' branches (a private Google Spreadsheet would be a good idea)? We can then curate all functions by the following pipeline:
1. Open '108_to_110' version.
2. Add the missing content from 'devel' version.
3. Check for the content, which we may have removed in 'devel' work.
4. Commit changes to 'devel' branch.

If you guys agree with the plan proposed, I can establish Google Spreadsheet and we can start fixing these functions asap. I can take care of IO and KEGG functions for a start.

**Comment by rasmusagren** [comment]
I think we can use git cherry-pick to select the commits that you've made in devel and then merge them into 108_to_110. I think it should give the fewest conflicts to handle.

**Comment by edkerk** [comment]
Ah, now I get it, your commit 825022697303acae726ad5df60d409343dd3e5e7 already shows the diff to master, it seems like you already _applied_ the 110 changes to the master version, instead of just uploading your 110 version.

So we should first cherry-pick devel to 108_to_110. I can do this, as most commits in devel are currently mine. Then, we should merge 108_to_110 to master (probably good to keep the same master branch, instead of renaming 108_to_110), perhaps checking one final time that the 110 changes make sense (using for instance git-blame to check the history of each file).

**Comment by edkerk** [comment]
I have cherry-picked devel to 108_to_110 (except from commit 4d0a94060b464b34bfa69e35345b0141b773ac3a, which shouldn't go to master).

The next step is merging 108_to_110 to master. I suppose we then also want to merge master to devel, to make sure that they are identical, so we can start "_fresh_" after this confusion with multiple branches?

Should we double check that the changes in commits 825022697303acae726ad5df60d409343dd3e5e7 and d272736fbb45ea7485d4d01e8c285a4924c9e199 did not break any development of the last year, before merging to master?

**Comment by rasmusagren** [comment]
Great! Could we sit down in person and look at this a little tomorrow? I feel that there is quite a big risk of something going badly here :) I’m available all day.

**Comment by edkerk** [comment]
Sounds good. I've booked the seminar room from 13:00, we could probably quickly go through each file diff, most of them are very low risk, and we can then focus on the few risky ones. **Anyone else is welcome/encouraged to join.** Just FYI: the solver part was done by Daniel, but he's no longer in the group.

**Comment by edkerk** [comment]
Just to inform, me and Rasmus will check a few more tricky functions and submit these to the 108_to_110 branch, hopefully we'll be done soon. Afterwards, this will be merged to master.

**Comment by rasmusagren** [comment]
I'm thinking of dropping support for exporting to xls (badly supported, binary, proprietary, mainly for Windows and old) and only keeping xlsx (open source, xml-based and much better support). MS introduced xlsx in Office 2007 so most people should use it by now. Since these formats are so vastly different they also require a lot of duplicate code for writing. Dropping xls would allow for better code reuse and maintenance and it would likely give fewer issues with platform incompatibilities. What do you think about this? Do you foresee problems with any of our tools, such as Biomet Toolbox or similar?

**Comment by simas232** [comment]
I strongly agree that we should leave only xlsx compatibility. During these two years I used RAVEN in macOS and Unix (Ubuntu/CentOS) and never had any problems with reading/writing xlsx files in these platforms.

**Comment by rasmusagren** [comment]
I've rewritten exportToExcelFormat from scratch and how several other Excel-using functions deal with loading libraries. I've also dropped support for xls. I think the code is neater now and I could remove quite a lot of redundant code, but it would maybe be good to validate if this works as intended. I did this on OSX, it would be great if someone on Windows could check out the 108_to_110 branch and test to first import and then export a model in Excel format. Thanks!

**Comment by rasmusagren** [comment]
Actually, import, export and then import again :)

**Comment by edkerk** [comment]
Works fine here. Import, export and them import again, no error messages, compareModels indicates that the models are identical.

**Comment by rasmusagren** [comment]
Great. I think I've completed "my" tasks now. I've rewritten how Apache POI is used and re-added the optimizeProb wrapper. I've removed the dependency on xlsread for all functions except for getExpressionStructure and getBlastFromExcel, which I didn't feel were worth the effort. I don't have a template file for those and they are very specific functions which could probably just as well be removed. Or kept as they are. Unless someone is very eager to purge xlsread once and for all that is :)

There were quite a lot of changes in parseTaskList, so if you have such a file laying around it would be great if someone could test that it gives the same results. Otherwise, does this mean that we could merge this branch?

On a separate note. I've seen that compartments, such as rxnComps or metComps are expressed as a vector of integers which are indexes in model.comps. I have a feeling that this was changed at one point to simply be the cell array of compartment ids directly. Have you done any work on this? It could also just be that I remember it wrongly :)

**Comment by edkerk** [comment]
Probably fine to remove getExpressionStructure and getBlastFromExcel, indeed not worth the effort to update.

I've never used parseTaskList, so can't help here.

metComps and rxnComps have been like they are since RAVEN 1.00. See line 119 in addMets.m now:

`t2=strcat(model.metNames,'***',model.comps(model.metComps));`

versus line 112 in version 1.01:

`t2=strcat(model.metNames,'¤¤¤',model.comps(model.metComps));`

metComps is used as index to comps.

I will make some last changes in the KEGG functions and commit this to 108_to_110.  After this, we can merge with master?

**Comment by rasmusagren** [comment]
You should, tasks are my favourite feature in RAVEN :)

Ok, then I just misremembered. I think we can merge. Thanks for your efforts!

**Comment by edkerk** [comment]
I committed the changes to KEGG functions. If there are no further comments, I will merge with master and devel at the end of today.

**Comment by edkerk** [comment]
Merged
