### ISSUE TITLE
fix: COBRA introduced a conflicting function with RAVEN

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/RAVEN#183]
### Description of the issue:
On the latest release of COBRA, the function [`removeGenes.m`](https://github.com/opencobra/cobratoolbox/commit/fd9c037d20f8e91561beeac3fb77b7671ee85fef#diff-f8fbd3f481593189c0ca41893138f015) was introduced, which conflicts with our own `removeGenes.m`.

**I hereby confirm that I have:**
- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by Hao-Chalmers** [comment]
@BenjaSanchez  could you give examples or descriptions to clarify the conflicts between them.

**Comment by BenjaSanchez** [comment]
@Hao-Chalmers the name is the same, so if I have both toolboxes in my Matlab path and I call let's say RAVEN's `removeGenes.m`, COBRA's `removeGenes.m` might be used instead

**Comment by simas232** [comment]
Should we ask COBRA developers to change the function name from their side? This function was introduced in RAVEN earlier than in COBRA, so I think we have a right to ask them so. The similar case was with `mergeModels` one year ago, @Hao-Chalmers asked them for function rename in COBRA and they did that.

**Comment by Hao-Chalmers** [comment]
Yes, I did that before for another function `mergeModels.m`. And this probably need to be done again.

But it seems this _issue_ should be addressed to **COBRA**, instead of **RAVEN**.

**Comment by tpfau** [comment]
One more reason to get #184 running :)
Sorry for that I'll have a look how I can rename this function.

**Comment by BenjaSanchez** [comment]
@Hao-Chalmers @simas232 thanks for the feedback, I was not sure where to raise the issue.

@tpfau thanks for the quick fix in https://github.com/opencobra/cobratoolbox/pull/1373

**Comment by laurentheirendt** [comment]
This is now fixed on the `develop` branch of the COBRA Toolbox. Thanks @BenjaSanchez for reporting and @tpfau for fixing! 👍

**Comment by Hao-Chalmers** [comment]
@laurentheirendt @tpfau thanks for the swift fixing. I think this issue has been nicely resolved.
