### ISSUE TITLE
style: rename function getINITModel

### ISSUE THREAD

**Issue by Hao-Chalmers** [SysBioChalmers/RAVEN#193]
### Description of the issue:
* There is a **RAVEN** function _`getINITModel`_ that reconstructs human GEMs based on omics data and/or predefined metabolic tasks. However, it appeares that the function name is inaccurate and misleading, given that the function actually implements the **tINIT** algorithm (described in `MSB 2014;10:721`) while there was a different/relevant algorithm **INIT** (described in `PLoS Comput Biol. 2012;8:e1002518`).

#### Expected feature/value/output:
* To reflect the actual algorithm and avoid ambiguity to users and the community, this function name should be adjusted. And the citation in function description need to be changed from `PLoS Comput Biol. 2012;8:e1002518` to `MSB 2014;10:721`
* This function is NOT called by any other **RAVEN** functions. A straight forward solution is changing the name to _`gettINITModel`_
* Developers and users (@danieljcook @JonathanRob ) are welcome to join the discussion, which may come up with an even better solution/name

**I hereby confirm that I have:**
- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)

**Comment by JonathanRob** [comment]
The "t" in "tINIT" refers to the metabolic tasks that the model must achieve. However, this input is optional, where excluding it will simply be the INIT algorithm with no tasks being run. I therefore don't see a reason to change the name, since the task piece is optional. Also, as a minor stylistic point, the "t" from "tINIT" is difficult to distinguish from the "t" in "get".

**Comment by Hao-Chalmers** [comment]
@danieljcook good idea to cite both papers.

@JonathanRob you clarified that the inclusion of metabolic tasks differs the **INIT** and **tINIT** algorithm, and this function implements the latter.

**Comment by edkerk** [comment]
So the criticism is that the name `getINITmodel` does not make obvious that it can generate **tINIT** models, but with the same argument `tINIT` does not make obvious that it can also generate non-t **INIT** models?

For backwards compatibility, it's better not to change function names too often (we already changed a lot for RAVEN 2 to ensure compatbility with COBRA).

Wouldn't it be better to just improve the documentation, specifically of the `getINITmodel` function, but maybe also have a little section in the Wiki. This would be good regardless, as it is at the moment quite unclear how to get started with generating (t)INIT models.

Note that the [`README.md`](https://github.com/SysBioChalmers/RAVEN/blob/master/README.md) does mention both papers.

**Comment by Hao-Chalmers** [comment]
@edkerk Renaming `getINITmodel` function should be irrelevant to the compatibility with COBRA, but does requires trading off between the backward compatibility and resolving ambiguity.

**Comment by Hao-Chalmers** [comment]
A further look shows that there is no function/script/code associated to the paper published in _2012_. 

This **tINIT** function was openly introduced in the _2014_ paper for the first time, although was already included in **RAVEN** 1.0 (_2013_). Literally there is no (public) function implementing **INIT** algorithm alone, and thus the _2012_ paper could be removed from `README.md` in my view.

**Comment by JonathanRob** [comment]
@Hao-Chalmers, the current function implements the **INIT** algorithm **by default**, whereas its **tINIT** functionality is **optional**. Since the 2012 paper describes the actual optimization algorithm used in INIT (and tINIT), I would recommend against removing its citation. I can say from personal experience that the 2012 paper has been more helpful in understanding the code than the 2014 paper.

**Comment by Hao-Chalmers** [comment]
It seems a consensus of citing both references has been reached, and was implemented in commit 
[06ead4f](https://github.com/SysBioChalmers/RAVEN/pull/170/commits/06ead4fcba958dde636ec1459a8f93bc24033dc6).

**Comment by edkerk** [comment]
Now in `devel`, will close this issue when it's implemented in master.

**Comment by Hao-Chalmers** [comment]
With the involvement from relevant parties, this issue has been well discussed and resolved as:

- Both references (`PLoS Comput Biol. 2012;8:e1002518` and `MSB 2014;10:721`) are cited
- The function name `getINITModel` is kept for backward compatibility, while the ambiguity still remains and expect to be mitigated from above discussion
- The implementation has been made by PR #170, and the issue is thus closed
