### ISSUE TITLE
question: ravenCobraWrapper handling of brackets when changing rules to grRules

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/RAVEN#198]
### Description of the issue:
*When using `ravenCobraWrapper` to change yeast model from cobra format to raven format, one bracket is missing in model.grRules.

#### Reproducing this issue:
matlab
navigate to yeastGEM repo:
model = loadYeastModel;
modelr = ravenCobraWrapper(model)

**model.rules in cobra format:**
```
'( x(352) | x(902) )'
'x(434)'
'x(401)'
'( x(242) & x(668) )'
```
**modelr.grRules in raven format:**
```
'YGR143W or YPR159W'
'YIL020C'
'YHR037W'
'YEL038W and YMR009W'
```
Look at the last one grRules, it is incorrect. When you run the wrapper again, it will change back to the cobra format. and model.rules are
```
'x(352) | x(902)'
'x(434)'
'x(401)'
'x(242) & x(668)'
```
It is inconsistent with what we started.

#### System information
* Please report:
1. RAVEN version 2.1.0 (stabile [release](https://github.com/SysBioChalmers/RAVEN/releases), `master` )
2. MAC

**I hereby confirm that I have:**
- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by tpfau** [comment]
Hi,
While the strings are different, the rules are the same. The parenthesis in the rules are not necessary, at least not in the cases you list. 
RAVEN normalises rules removing unnecessary parenthesis to make rule parsing later on easier.

**Comment by feiranl** [comment]
Okay, so the rules should be kept without the outer bracket, even though they are isoenzymes and complexes?

**Comment by edkerk** [comment]
@feiranl Thanks for reporting this! But as explained by @tpfau, this is not a bug but a feature, where RAVEN discards unnecessary brackets, without changing the logic. In nested grRules (e.g. `A and ( B or C) and D`) the brackets are kept.
