### ISSUE TITLE
Tutorial Exercise 5 missing

### ISSUE THREAD

**Issue by lavik17** [SysBioChalmers/RAVEN#206]
I have downloaded Raven Toolbox 2 and it seems that the file of Excercise 5 in the tutorial is missing from the tutorial folder.

**Comment by Hao-Chalmers** [comment]
@lavik17 check out the last sentence of `RAVEN mini tutorial.docx` file, it says "See the `tutorial2018.m` file for details".

**Comment by edkerk** [comment]
See @Hao-Chalmers reply, no problem exists, the file is present.
