### ISSUE TITLE
help: solveLP not working with Mosek

### ISSUE THREAD

**Issue by ksye** [SysBioChalmers/RAVEN#208]
While running the tutorial files I get the following error message:
 ``` matlab
Error using dispEM (line 50)
The number of fluxes and the number of reactions must be the same


Error in printFluxes (line 69)
    dispEM(EM);

Error in tutorial0 (line 90)
printFluxes(model, sol.x, false, 10^-7); %true means only print exchange fluxes
```

I have performed the installation verification and nothing seems to be wrong.

 ``` matlab
*** THE RAVEN TOOLBOX v. 2.0 ***

Checking if RAVEN is on the Matlab path... PASSED
Checking if it is possible to parse a model in Microsoft Excel format... PASSED
Checking if it is possible to import an SBML model using libSBML... PASSED
Solver found in preferences... mosek
Checking if it is possible to solve an LP problem using gurobi... FAILED
Checking if it is possible to solve an LP problem using mosek... PASSED
Checking if it is possible to solve an LP problem using cobra... FAILED
Preferred solver... KEPT
Solver saved as preference... mosek

Checking the uniqueness of RAVEN functions across Matlab path...
No conflicting functions were found
```
Could anyone help me understand what's wrong? Thank you! 

[edited by @edkerk for formatting]

**Comment by edkerk** [comment]
You get an error message from `printFluxes` on line 90, while in the distributed [`tutorial0.m`](https://github.com/SysBioChalmers/RAVEN/blob/master/tutorial/tutorial0.m) this function is on line 89. Could you please ensure that you haven't made any changes to `tutorial0.m`?

**Comment by ksye** [comment]
Hi, thanks for the quick answer! I re-downloaded the whole package and substituted the old tutorial0.m file for the fresh download one and the error message was as you said 
```

> Error using dispEM (line 50)
> The number of fluxes and the number of reactions must be the same
> 
> 
> Error in printFluxes (line 69)
>     dispEM(EM);
> 
> Error in tutorial0 (line 89)
> printFluxes(model, sol.x, true, 10^-7); %true means only print exchange fluxes

If I recall I have commented every line bellow the error line in an attempt to debug it by myself. 
Again thank you for helping! 

```

**Comment by edkerk** [comment]
@ksye can you please run `tutorial0.m` until line 88 and then run the commands below and post the results?

```matlab
size(model.rxns)
sol.f
size(sol.f)
```

Also, what operating system and Matlab version are you using?

**Comment by edkerk** [comment]
Ok, so the problem is with `solveLP`, it doesn't return a solution.
Let's first test whether the earlier commmands (lines 56, 70 and 73) worked.

Run the tutorial until line 74 and then give the output from the following commands:

`[length(model.rxns) length(model.mets)]` (output should be `1632 1395`)

`model.ub(getIndexes(model,{'glcIN' 'etohIN' 'co2OUT'},'rxns'))` (output should be `1 0 1000`)

`find(model.c)` (output should be `1485`)

If you get the same output, what is then the result of the following command:

`solveLP(model)`

**Comment by ksye** [comment]
The output was the following 

> \>> [length(model.rxns) length(model.mets)]
> 
> ans =
> 
>         1305        1037
> 
> >> model.ub(getIndexes(model,{'glcIN' 'etohIN' 'co2OUT'},'rxns'))
> 
> ans =
> 
>            1
>            0
>         1000
> 
> >> find(model.c)
> 
> ans =
> 
>         1285
> 
> >> 

Which is different from the expected except for the upper bounds from what I understand.

**Comment by ksye** [comment]
The output was:
> ans = 
> 
>        x: []
>        f: []
>     stat: -1
>      msg: 'The problem is infeasible'

**Comment by edkerk** [comment]
Hmm. I wonder if there is a problem with the solver? Do you get the same results with the following lines (make sure to run this from the `tutorial` subfolder, check with `pwd()`):

```matlab
>> load('iMK1208.mat')
>> sol=solveLP(iMK1208)

sol = 

  struct with fields:

       x: [1859×1 double]
       f: -0.0699
    stat: 1
     msg: 'Optimal solution found'
```

Have you tried installing an alternative solver, e.g. Mosek? Then change the solver using `setRavenSolver`. In case you also have [cobratoolbox](https://github.com/opencobra/cobratoolbox) installed, you can also set `setRavenSolver('cobra')` to use cobra's solver.

**Comment by ksye** [comment]
I've been using Mosek initially, but have now installed Gurobi and tested the tutorial code and it finally worked! Seems like there was some problem with the Mosek installation probably. 

Thank you very much for your time and help!
