### ISSUE TITLE
feat: re-format the MetaCyc dump file allowing for convenient balancing info extraction

### ISSUE THREAD

**Issue by Hao-Chalmers** [SysBioChalmers/RAVEN#211]
### Description of the issue:
The _de novo_ reconstruction modules in RAVEN utilize the database dump files for automated draft model generation. In contrast to **KEGG**, **MetaCyc** provides manually curated and chemically balanced reactions, which amount to over 90% collected reactions in the database. Among the unbalanced reactions in **MetaCyc**, some can be easily recognized by the slot of `CANNOT-BALANCE? - T` while the others that are also undermined (e.g. peptidase catalyzing type or  with non-numerical coefficient) but cannot be discerned from the rest, due to lack of identifying attribute in the dump file. So far, a compromise solution is to extract these undetermined reactions using the desktop software Pathway Tools while generating `.mat` database files. However, the optimal solution is to contact the curators in SRI for adding additional slot into the reaction dump file so that all reaction types can be directly parsed.

**I hereby confirm that I have:**
- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by Hao-Chalmers** [comment]
A positive feedback has been obtained from reaching out MetaCyc curators, as below:

>From: Suzanne Paley <paley@AI.SRI.COM>
>Sent: Thursday, January 24, 2019 7:26 PM
>To: Hao Wang; ptools-support@ai.sri.com
>Cc: Ron Caspi
>Subject: Re: [ptools-support] [External Sender] Flag undetermined reactions in dump file
> 
>Hi Hao,
>
>Thanks for the feedback.  We are planning to add an additional attribute 
>to the file that indicates whether each reaction is balanced, unbalanced 
>or undetermined.  I believe this should be in place in time for our next 
>release.  I hope this addresses your needs.
>
>Suzanne
>
>On 1/21/19 12:59 PM, Hao Wang wrote:
>> Hello,
>>
>> MetaCyc is a valuable resource hosting a collection of reactions/pathways with experimental evidence. Here I would like to provide a suggestion regarding the format of MetaCyc reaction dump file “reactions.dat”, in order to assist convenient parsing of reaction balancing information.
>>
>> Most reactions (> 90%) in MetaCyc are curated as chemically balanced, which is great. The rest (~8 %) are unbalanced and can be largely separated into two groups: group1 includes either polymeric reactions or with specific difficulty in balancing class structures, and are clearly indicated by attribute slot of “CANNOT-BALANCE? - T”; whereas group2 are undermined because they are either peptidase catalyzing type or with non-numerical coefficient and/or unknown structure, unfortunately these ones are left out without any indications in the dump file (they can be located by Pathway Tools though). My recommendation is to clearly flag these group2 reactions by existing attribute (e.g. "CANNOT-BALANCE? - Undetermined") or introducing new attribute. This would allow convenient extraction of relevant information and assist downstream applications in the long run.
>>
>> Please let me know if you have any questions regarding this suggestion and look forward to your responses.
>>
>> Best regards,
>> Hao

**Comment by simas232** [comment]
@Hao-Chalmers, I think such issue may be fixed by ourselves as well, since it doesn't take much time to quickly identify elementally unbalanced reactions. This can be done for KEGG as well.

**Comment by Hao-Chalmers** [comment]
The MetaCyc version **23.0** was just released with the inclusion of detail reaction balancing information. The MetaCyc-based reconstruction module in `RAVEN` will thus be updated and adjusted accordingly.

**Comment by edkerk** [comment]
@Hao-Chalmers I assume that we can then close this issue?

**Comment by Hao-Chalmers** [comment]
@edkerk keep it open, it's not done.

**Comment by edkerk** [comment]
Sorry, didn't realize that #224 being closed means that it was not merged.

**Comment by Hao-Chalmers** [comment]
Now this issue has been resolved in #224.
