### ISSUE TITLE
help: how to perform robust analysis in raven. 

### ISSUE THREAD

**Issue by kabilan2818** [SysBioChalmers/RAVEN#219]
[copied by @edkerk from [comment](https://github.com/SysBioChalmers/RAVEN/issues/219#issuecomment-487356432) below:]

in cobra toolbox we can perform robustness analysis
doubleRobustnessAnalysis(model, controlRxn1, controlRxn2, nPoints, plotResFlag, objRxn, objType)

is there any way to perform similar kind in raven toolbox.
and one of my interested metabolite is essential metabolite for biomass. is there any possible way to perform gene deletion analysis as if i give obj function as biomass, all the flux for the interested metabolite moves towards biomass. if i give obj function as interested metabolite then there is no biomass formation.

how to perform dual objective function analysis for both biomass and interested metabolite.
Thank you
Regards 
Kabilan

**Comment by edkerk** [comment]
@kabilan2818 could you please edit your post and explain what you are exactly looking for?

**Comment by kabilan2818** [comment]
in cobra toolbox we can perform robustness analysis
doubleRobustnessAnalysis(model, controlRxn1, controlRxn2, nPoints, plotResFlag, objRxn, objType)

is there any way to perform similar kind in raven toolbox.
and one of my interested metabolite is essential metabolite for biomass. is there any possible way to perform gene deletion analysis as if i give obj function as biomass, all the flux for the interested metabolite moves towards biomass. if i give obj function as interested metabolite then there is no biomass formation.

how to perform dual objective function analysis for both biomass and interested metabolite.
Thank you
Regards 
Kabilan

**Comment by edkerk** [comment]
@kabilan2818 RAVEN doesn't have the `doubleRobustnessAnalysis` functionality, because COBRA already has it! You can first run `ravenCobraWrapper` on your model to ensure it is in the COBRA format before running this function.

Regarding forced dual objective function, one approach would be to describe a pseudoreaction with both biomass and interesting metabolite as substrates, or enforce production of either of them by setting non-zero lower-bounds for their respective reactions.

**Comment by simas232** [comment]
@kabilan2818, take a look to `FSEOF` function, this may help you to identify gene deletion targets.

**Comment by Hao-Chalmers** [comment]
@kabilan2818 the `FSEOF` does help, but in identifying overexpression targets @simas232.

**Comment by kabilan2818** [comment]
Thank you all with the help of ravenCobraWrapper i could perform after converting raven model to cobra.
what is FSEOF function.
And how to convert .xml file of raven version to .xlxs format.

Thank you in advance

**Comment by Hao-Chalmers** [comment]
In RAVEN, you may import the model with function `importModel` and then convert it to .xlxs format with  `exportToExcelFormat`.

**Comment by kabilan2818** [comment]
while using FSEOF function in raven toolbox for predicting over expression targets, the results predicts  slope, direction (0,1,-1) and so on. what does it means for each direction and slope.

**Comment by kabilan2818** [comment]
Slope	rowID	Enzyme ID	Enzyme Name	Subsystems	Direction	Gr Rule
0.83994	6	ASADi	aspartate-semialdehyde dehydrogenase, irreversible	Alanine and Aspartate Metabolism	0	PAS_chr3_0471
0.83994	8	ASPKi	aspartate kinase, irreversible	Alanine and Aspartate Metabolism	0	PAS_chr4_0150
2.2631	10	ASPTAm	aspartate transaminase	Alanine and Aspartate Metabolism	-1	PAS_chr1-1_0200
1.8342	136	FUM	fumarase	Citric Acid Cycle	1	PAS_chr3_0647
