### ISSUE TITLE
help: meaning of slope and direction in output FSEOF function

### ISSUE THREAD

**Issue by kabilan2818** [SysBioChalmers/RAVEN#220]
simulation with FSEOF function predicts results which denotes slope and direction(0,1,-1). 
1)what does it means. Is increase in slope value represent more favorable for overexpression. any slope limit is there.

2)the direction represents (0,1,-1 ) what these three types of direction means
[fseof.txt](https://github.com/SysBioChalmers/RAVEN/files/3155535/fseof.txt)

**Comment by Hao-Chalmers** [comment]
@kabilan2818 the `FSEOF` function is an implementation of the method introduced in this [paper](https://aem.asm.org/content/76/10/3097), which developed an approach for identifying over-expression targets through scanning model fluxes according to the given target metabolite production (i.e. `targetRxn`).

> 1)what does it means. Is increase in slope value represent more favorable for overexpression. any slope limit is there.

The `Slope` value represents the ratio of flux change of the selected reaction to that of the target reaction. It gives the proportional changes required in selected reaction to obtain the desired changes in the the target reaction. Slope value does indicate the correlation between over-expression candidate reaction and the target reaction, but Not causal association. There is no limit to this value.

> 2)the direction represents (0,1,-1 ) what these three types of direction means

The direction value interprets the selected reaction and desired flux as such:
0 – irreversible reaction
1 – reversible reaction, from reactants to products
-1 – reversible reaction, from products to reactants

**Comment by kabilan2818** [comment]
thank you so much @Hao-Chalmers . as u said The Slope value represents the ratio of flux change of the selected reaction to that of the target reaction. it means that for example if the targeted metabolite production is pyruvate and the objective function is biomass formation, the change in flux of obj function of biomass without considering pyruvate and considering pyruvate. is it correct.

**Comment by kabilan2818** [comment]
thank you @Hao-Chalmers. Is that any coding for applying the flux in the visualization map of a single simulation. drawMap apply for comparing two different simulation but i need for single simulation

**Comment by simas232** [comment]
@kabilan, you can still use `drawMap` for a single simulation. Just leave `conditionB` parameter blank, see `drawMap.html` for more details.

**Comment by kabilan2818** [comment]
thankyou @Hao-Chalmers

**Comment by kabilan2818** [comment]
@Hao-Chalmers, on using FSEOF function ,it predicts the over-expression targets through scanning model fluxes according to the given target metabolite production. my question is
1)How to analyse each predicted gene targets.
2)is there any coding for predicting the flux change for biomass and target rxn.

**Comment by Hao-Chalmers** [comment]
> 1)How to analyse each predicted gene targets.

These candidate genes can be subjected for experimental verification, preferably after literature checking.

>2)is there any coding for predicting the flux change for biomass and target rxn.

So far, there is no such code in FSEOF function.
