### ISSUE TITLE
bug: conflict in duplicate function name: getVersion

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#233]
### Description of the issue:
MATLAB 2018b (presumably also in later versions, possibly also in earlier versions) comes with matlabxl toolbox that has a function with the name `getVersion`. This is conflicting with `getVersion` as distributed by RAVEN in the `io` subfolder. Easies solution would be to rename the RAVEN function.

#### Reproducing this issue:
```matlab
checkFunctionUniqueness
```

#### System information
1. RAVEN version 2.2.2
2. At least MATLAB 2018b with matlabxl toolbox installed

**I hereby confirm that I have:**
- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)

**Comment by simas232** [comment]
Maybe `getToolboxVersion`?

**Comment by edkerk** [comment]
Change to `getToolboxVersion` is a good suggestion. To my knowledge, this function is only called by `exportForGit`, so should be easily fixed.
