### ISSUE TITLE
Master list of RAVEN biochemistry identifiers

### ISSUE THREAD

**Issue by samseaver** [SysBioChalmers/RAVEN#247]
I can see that RAVEN uses a numbering system for the identification of metabolites added to models such as in `core/addMets.m`, but I can also see that in models such as iAL1006 there is an unique identification scheme, for example, the use of `AKG` to represent 2-oxoglutarate.

I was searching for a master list of these metabolites, their identifiers, and possibly their mappings to other external databases such as KEGG, but I can't see to find one, do you maintain one?

**Comment by edkerk** [comment]
RAVEN does not have its own system of identifiers, it uses the identifiers that are provided by the model, or which are provided by the user.

If a new metabolite is added by `addMets`, and the user does not provide metabolite identifiers in `metsToAdd.mets`, the by default it will use a prefix, underscore and number (e.g. `m_0001`), where the numbering is sequential (second metabolite added: `m_0002`, etc.), as long as the metabolite identifiers are unique to the model.

So no master list exist for these identfiers, as they will be different for each model. Instead, metabolite annotations that are stored in`metMiriams` can be used to map metabolites to different databases, but these annotations should also be provided in the model file.

**Comment by samseaver** [comment]
This took me a little while to get my head around, since there are a number of published models that share the same biochemical identifiers as the iAL1006 but I now realize that these identifiers came from the original models that were used to generate iAL1006.
