### ISSUE TITLE
feat: zenodo storage

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#263]
### Description of the issue:
For long term storage, should stabile releases be automatically submitted to [Zenodo](https://zenodo.org/)?

**Comment by simas232** [comment]
I agree that we should implement this. Just like in [yeast-GEM](https://github.com/SysBioChalmers/yeast-GEM), the users would be able to quickly cite the RAVEN version they use in their work. Does Zenodo implementation require the first time setup only or would we need to manually push changes for every upcoming RAVEN release?

**Comment by simas232** [comment]
@edkerk, I think we should already implement Zenodo for the upcoming RAVEN release. Could you please flip the switch for RAVEN repository in Zenodo?

**Comment by edkerk** [comment]
I've flipped the switch on Zenodo, next release should be captured by them. Once released and available on Zenodo, a DOI will be associated to RAVEN on Zenodo, and then we can create a badge to add to the readme.
