### ISSUE TITLE
Help: How to the .XML file generated by CellDesigner into a .mat file?

### ISSUE THREAD

**Issue by wenjuanmo** [SysBioChalmers/RAVEN#269]
For the RAVEN to draw pathway maps in Matlab, the .mat pathway file is needed. However, the CellDesiger software only export XML files, how to transform the XML file into mat file？

**Comment by Hao-Chalmers** [comment]
Not sure about the format of XML files exported from CellDesigner.

If the XML files are models compatible with SBML spec (level2 or level3), one can use RAVEN function `importModel` to import into Matlab.

**Comment by simas232** [comment]
@wenjuanmo, have a look into `constructPathwayFromCelldesigner` function. This should help you to convert CellDesigner XML file to mat format.

**Comment by wenjuanmo** [comment]
Thanks a lot for these helpful replies.
