### ISSUE TITLE
checkInstallation solver choice

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#27]
It now sets the solver to gurobi, even if both gurobi and mosek failed. This seems misleading. Also, it doesn't check whether 'cobra' is an option. This should probably be coded as third solution. Finally, if libSBML fails then the solvers also fail. Instead, when libSBML fails the script should load a .mat model and attempt the solvers on those.

**Comment by simas232** [comment]
Fixed an issue, when LP solver functionality check depended on libSBML. Now LP solver is tested by loading the model from empty.mat, thereby circumventing libSBML.
Commit b5ddd2efdd2c1e60f8c131d63f44bc1758573616

**Comment by simas232** [comment]
The solver choice is now set to 'none' if there are no working LP solvers available. Also added 'cobra' as the third choice for setRavenSolver.

Commit 511867c819d69a71baef642bceb234aa0e1b720e
