### ISSUE TITLE
bug: broken links for Pre Trained HMMs

### ISSUE THREAD

**Issue by NeeluBegum** [SysBioChalmers/RAVEN#305]
### Description of the issue:

The link to download Pre trained HMMs is broken. release 94.0 to be precise

**Comment by edkerk** [comment]
Downloading the pre-trained HMMs for release 94.0 seems to work fine here. @NeeluBegum could you please complete the whole Issue template, by providing the information below, so we can figure out what exactly happens in your case?

#### Reproducing this issue:
```matlab
INSERT THE COMMAND THAT YOU RAN
```

#### System information
* Please report:
1. RAVEN version (stabile [release](https://github.com/SysBioChalmers/RAVEN/releases), `devel` branch?)
2. Operating system (Windows/Mac/Linux; include version)

**Comment by simas232** [comment]
I checked the links and they are not working. @ckitti, could you please have a check in this?

**Comment by edkerk** [comment]
All the links seem to work here?

As taken from `getKEGGModelForOrganism.m`:
euk100_kegg94: https://chalmersuniversity.box.com/shared/static/wbnghgtpgftb6pcw572bhkl9a8ekh32d.zip
euk90_kegg94: https://chalmersuniversity.box.com/shared/static/754bdz0965261fktzlwc77rcv7me87i6.zip
euk50_kegg94: https://chalmersuniversity.box.com/shared/static/5xwgv17cn099xn7bxo2dq5h1dsdxrhn7.zip
prok100_kegg94: https://chalmersuniversity.box.com/shared/static/azpn5lwrb4gind2mn5hnbmux0lao5vt5.zip
prok90_kegg94: https://chalmersuniversity.box.com/shared/static/j19ybilr7js34uisnss92gvq5g6lljkk.zip
prok50_kegg94: https://chalmersuniversity.box.com/shared/static/b5vn631jrwdzcj4uwmvbshe2ws3zoalm.zip

**Comment by simas232** [comment]
The links work for me as well.

Could it be that files stored in Box Sync are not available upon their maintenance routines? Mirror links may help to minimize this problem, but we got only a few such reports during the recent 2.5 years, suggesting that links are OK for most of the time.

**Comment by edkerk** [comment]
Could be, but considering this rarely happens it's not really worth the effort? Easier to make `getModelFromHomology` to throw an informative error message, probably good to code that anyway. I'm not sure what error message you and others encountered when the link didn't work, but this is what I could fake:

```matlab
>> websave('here.zip','https://chalmersuniversity.box.com/shared/static/nonExistingFile.zip')

Error using matlab.internal.webservices.HTTPConnector/copyContentToFile (line 389)
The server returned the status 404 with message "Not Found" in response to the request to URL
https://chalmersuniversity.app.box.com/public/static/nonExistingFile.zip.

Error in websave (line 107)
copyContentToFile(connection, filename);
```

So we could put `websave` in a `try ... catch` statement, catch ME with identifier `MATLAB:webservices:HTTP404StatusCodeError` and instead throw an error message that informs that the link is not working, try again in a little while, if it remains not working then please report this on the RAVEN GitHub Issues page.

**Comment by simas232** [comment]
I recall that the error was "Not found" type. @edkerk, your idea regarding `try`, `catch` usage in `getKEGGModelForOrganism` is great. If `try` portion is unsuccessful, `catch` might notify about the error and advice users to report such case in Gitter RAVEN chat room.

**Comment by edkerk** [comment]
Alright, I'll add it to my to do list :)
