### ISSUE TITLE
chore: DIAMOND error -1073741515

### ISSUE THREAD

**Issue by lzh0321** [SysBioChalmers/RAVEN#306]
### Description of the issue:
Hello!
I use `getMetaCycModelForOrganism` to reconstruct the model, I use my protein sequence (.faa), but the run result shows an error:
```matlab
Error getDiamond (line 88)
         dispEM(EM,true);
Error getMetaCycModelForOrganism (line 84)
         blastStruc=getDiamond(organismID,fastaFile,{'MetaCyc'},fullfile(ravenPath,'metacyc','protseq.fsa'));
```
What should I do? Thanks!
#### Reproducing this issue:
```matlab
getMetaCycModelForOrganism
```

#### System information
* Please report:
1. RAVEN version: 2.4.0
2. Operating system: Windows 10

**I hereby confirm that I have:**
- [ ] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [ ] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by Hao-Chalmers** [comment]
Can you make sure if your query `faa` file is under current path when running the `getMetaCycModelForOrgansim` function?

**Comment by lzh0321** [comment]
> Can you make sure if your query `faa` file is under current path when running the `getMetaCycModelForOrgansim` function?

yes,I can.

**Comment by lzh0321** [comment]
sorry,I miss an error: 
DIAMOND makedb did not run successfully, error: -1073741515

**Comment by Hao-Chalmers** [comment]
In order to reproduce the error, can you also notify us your OS and Matlab version?

**Comment by lzh0321** [comment]
OK,Windows 10,Matlab R2019a,RAVEN 2.4.0

**Comment by Hao-Chalmers** [comment]
To rule out DIAMOND issues, can you run the `testDiamond` function in your environment see if you get errors.

**Comment by lzh0321** [comment]
Testing DIAMOND makedb... Not OK
error use dispEM (line 50)
DIAMOND makedb did not run successfully, error: -1073741515

**Comment by edkerk** [comment]
Works fine here on Windows, so doesn't seem to be a general problem with DIAMOND on Windows 10. The error message seems to have something to do with "[the inability of an executable program to run due to missing essential components (one or many .dll files) or wrongly configured system files"](https://windowsreport.com/file-system-error-1073741515/#:~:text=File%20System%20Error%201073741515%20%2C%20which,or%20wrongly%20configured%20system%20files.)". On the [DIAMOND website](http://www.diamondsearch.org/index.php?pages/installation/) is mentioned that Visual C++ Redistributable should be installed, is that the case @lzh0321?

**Comment by Hao-Chalmers** [comment]
@edkerk thanks for the investigation. Then this is not a bug of RAVEN, but DIAMOND installation issue.

**Comment by lzh0321** [comment]
OK，I will try. Thank you very much for your help! @Hao-Chalmers @edkerk

**Comment by edkerk** [comment]
@lzh0321 Could you please report back whether installation of Visual C++ Redistributable solves your issue, we could then automatically include this suggestion when this error code is encountered in Windows. Thanks!

**Comment by lzh0321** [comment]
Hello, I looked up my computer found Visual C++, and I reinstalled it, but the result also error. I refixed the system and the result is the same. I used three other computers, and it all turned out like this.

**Comment by simas232** [comment]
@lzh0321, could you please run `checkInstallation` and write us the full output here? Let's see if this problem is only related to DIAMOND or more general problem.

**Comment by lzh0321** [comment]
*** THE RAVEN TOOLBOX v.2.4.0 ***

Checking if RAVEN is on the MATLAB path...									OK
Checking if it is possible to parse a model in Microsoft Excel format...	OK
Checking if it is possible to import an SBML model using libSBML...			Not OK
To import SBML models, download libSBML from
http://sbml.org/Software/libSBML/Downloading_libSBML and add to MATLAB path
Solver found in preferences... none
Checking if it is possible to solve an LP problem using gurobi...			Not OK
Checking if it is possible to solve an LP problem using cobra...			Not OK
WARNING: No working solver was found!
Install the solver, set it using setRavenSolver('solverName') and run checkInstallation again
Available solverName options are 'mosek', 'gurobi' and 'cobra'

Checking essential binary executables:
NOTE: Broken binary executables must be fixed before running RAVEN
	makeblastdb.exe...							OK
	blastp.exe...								OK
	diamond.exe...								Not OK! Download/compile the binary and run checkInstallation again
	hmmsearch.exe...							OK
Checking non-essential/development binary executables:
NOTE: Only fix these binaries if planning to use KEGG FTP dump files in getKEGGModelForOrganism
	cd-hit.exe...								OK
	mafft.bat...								Not OK! If necessary, download/compile the binary and run checkInstallation again
	hmmbuild.exe...								OK

Checking whether RAVEN functions are non-redundant across MATLAB path...	Not OK
WARNING: Duplicate functions in D:\cobra toolbox\cobra toolbox\external\m2html: 
    'm2html.m'
    'mdot.m'

Not OK
WARNING: Duplicate functions in D:\cobra toolbox\cobra toolbox\src\reconstruction\refinement: 
    'removeGenes.m'

It is strongly recommended to resolve conflicting functions as this may compromise RAVEN functionality

*** checkInstallation complete ***

**Comment by simas232** [comment]
Ok, we can conclude that this is not RAVEN or MATLAB issue, but merely an issue related to DIAMOND functionality in Windows. You can therefore try replacing the existing `diamond.exe` in `RAVEN/software/diamond` with the latest official DIAMOND version available [here](https://github.com/bbuchfink/diamond/releases). If it still doesn't work in your computer, please contact [the developer](https://github.com/bbuchfink). The RAVEN-provided `diamond.exe` was downloaded from the same source and the DIAMOND developer should know more how to fix this issue.

**Comment by NagihanMatlab** [comment]
@lzh0321 did you solve the problem? I am also facing the same problem, if you have any suggestions would you help me? Many thanks.

**Comment by simas232** [comment]
@NagihanMatlab, please read my last comment as this is not RAVEN, but the DIAMOND issue.
