### ISSUE TITLE
Issue regarding getBlast

### ISSUE THREAD

**Issue by vetles** [SysBioChalmers/RAVEN#31]
When trying to perform a bidirectional BLASTp between a query (.fa file) a target set (.fasta file) using the getBlast function, I get the following error message:

Error using importdata (line 136)
Unable to open file.

Error in getBlast (line 86)
        A=importdata([outFile '_' num2str(i)]);
 
Is there anyone who has experienced a similar scenario, and are there any ways to fix this?

**Comment by edkerk** [comment]
Most likely is that the query and target files are not in the current folder. `pwd` will show you your current folder, and `dir` shows you which files are in this folder. Ensure that the two FASTA files are both in this folder.

If this does not solve your problem, can you please provide some more information?

- RAVEN version
- Operating system and version
- MATLAB version

**Comment by vetles** [comment]
Both the query and target files are in the current folder, so this doesn't seem to be the issue. I am currently using:

- RAVEN Toolbox v. 2.0.0-alpha

- MATLAB 2016b

- Windows 10, version 1703 (OS-build 15063.674)

**Comment by edkerk** [comment]
Please download the latest version from: https://github.com/SysBioChalmers/RAVEN/tree/raven2. getBlast should now be more specific about where it fails. (Your error message indicates that it fails to read the output files from BLAST, but it is not clear where it exactly failed).

**Comment by Hao-Chalmers** [comment]
This might be related to the access rights to the temporary folder in Windows, which could happen on a computer without administrator privilege.

BTW, you may have a look the Figure5_ver3 at the shared folder, which was just updated based on your comments.

**Comment by vetles** [comment]
I downloaded the latest version of RAVEN, and the function worked fine. Thank you so much for helping out.

**Comment by edkerk** [comment]
No problem, thanks for using RAVEN and reporting issues.
