### ISSUE TITLE
Empty draft model from getModelFromHomology

### ISSUE THREAD

**Issue by vetles** [SysBioChalmers/RAVEN#32]
I'm having some issues using the function getModelFromHomology. When using a template model, as well as a blast structure generated from getBlast as input arguments, the function only returns an empty draft model. I've made sure that the gene names in the blast structure is compatible with the gene names in the template model. Has anyone experienced similar problems with getModelFromHomology?

I am using:

- MATLAB 2016b

- Windows 10, version 1703 (OS-build 15063.674)

- RAVEN Toolbox v. 2.0

**Comment by edkerk** [comment]
The most common issue is indeed that gene names are not in the same format. You indicate that this is fine.

Another issue is that the model ids that you specify in getBlast should match the ones you specify when running getModelFromHomology.

Example:
`templateModel.id`  check model ID of template model. Let's say it's:  `'tmp'`

`blastStructure = getBlast('new', 'new_organism.fasta', {'tmp'}, {'template_organism.fasta'});`
`draftModel = getModelFromHomology(templateModel, blastStructure, 'new');`

Finally, if you use a template model from an organism that is very distant from your organism of interest, it might be that none of the blast results pass the cutoffs. You can lower the cutoffs (maxE, minLen and minSim) as parameter settings in getModelFromHomology.

**Comment by simas232** [comment]
Another reason could be that the model is inappropriately fed to getModelFromHomology. Before running getModelFromHomology, put your template model to another cell array structure:

`templateModelList{1}=templateModel;`

and then try to run getModelFromHomology while giving templateModelList as the first parameter

**Comment by vetles** [comment]
I've made sure that the template model is in the format of a cell array. The ID fields of the template model and the blast structure are identical, as well as the ID of the organism of interest and the corresponding ID in the blast structure.

The organisms are closely related, and I've made sure that the blast structure contains significant matches involving genes that are a part of the template model reconstruction.

**Comment by simas232** [comment]
What about the blast structure, which you get from getBlast:

a) If you open it, do you have both non-blank fromId to toId in the first row?
b) Also check fromGenes and toGenes. Is everything fine with the gene names of the template organism?

**Comment by vetles** [comment]
a) The fromId of field 1 contains the ID of my template organism ('Aurli1'), and toId of the same field contains the ID of my organism of interest ('T66'). The second field contains the IDs in the reverse orientation.

b) Originally, the gene names weren't compatible with the gene names of the template model, so I made a small script to make them so (just removed some appending characters).

**Comment by simas232** [comment]
Dear @vetles,

This case requires more thorough evaluation. Could you put both multi-fasta files (for the target and template organisms) with your template model into the archive and upload it here?

**Comment by vetles** [comment]
@simas232 

I contacted you by e-mail where you will find the files, as well as some supplementary information.

**Comment by simas232** [comment]
After the personal communication with @vetles we found that the protein sequences in multi-fasta file for target organism were not named exactly like genes in template model. After fixing this, we were able to generate the draft model for the target species.
