### ISSUE TITLE
I am having a problem with the diamond.exe file. I could not find a way to run it. Any suggestions on this?

### ISSUE THREAD

**Issue by NagihanMatlab** [SysBioChalmers/RAVEN#321]
### Description of the issue:
*Try to be as clear as possible, e.g.:
- Is there a functionality missing?
- Did an existing function fail?
- What is the exact error message, and other output that you got?
- What have you tried yourself to fix it?

#### Reproducing this issue:
*If applicable, please attach the problematic code. PLEASE DELETE THIS LINE.*
```matlab
INSERT CODE HERE
```

#### System information
* Please report:
1. RAVEN version (stabile [release](https://github.com/SysBioChalmers/RAVEN/releases), `devel` branch?)
2. Operating system (Windows/Mac/Linux; include version)

**I hereby confirm that I have:**
- [ ] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [ ] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

*Note: replace [ ] with [X] to check the box. PLEASE DELETE THIS LINE*

**Comment by simas232** [comment]
Glad you had your issue solved. Feel free to reopen this issue if you encounter the same error again...
