### ISSUE TITLE
Help: whether it is possible to skip HMM search, and use the K number provided by myself.

### ISSUE THREAD

**Issue by PandengWang** [SysBioChalmers/RAVEN#336]
Thanks for providing this useful tool!

I didn't have genome sequence but got a list of (kegg) K numbers for one microbial species. 
So, I want to know whether it is possible to construct a metabolic network for this species with just a list of K numbers?

Thanks so much.

Best regards,
Pandeng

**Comment by Hao-Chalmers** [comment]
@PandengWang it is possible to construct a metabolic network using a list of K numbers. Here is one approach with following steps:

1.  extract involved reactions ids from the given list of K numbers (this step requires additional coding);
2. construct a reference metabolic network based on all information included in KEGG by using the [getModelFromKEGG](https://github.com/SysBioChalmers/RAVEN/blob/master/external/kegg/getModelFromKEGG.m) function;
3. get a species-specific network by subtracting the other reactions from the reference metabolic network by [removeReactions](https://github.com/SysBioChalmers/RAVEN/blob/master/core/removeReactions.m) function.

**Comment by PandengWang** [comment]
@Hao-Chalmers Thanks so much for your quickly reply. I will give it a try.
