### ISSUE TITLE
Availability of HMMs for KEGG

### ISSUE THREAD

**Issue by junhuili** [SysBioChalmers/RAVEN#34]
Hello,

I tried to download the HMMs, but the message of 'biomet-toolbox.org is coming soon' showed up. I wondered whether there is another way to download these HMMs?

Thanks in advance,
Junhui

**Comment by edkerk** [comment]
Dear Junhui,

We have developed version 2 of the RAVEN toolbox, which can now automatically download different sets of KEGG HMMs from our servers. Please get this version from https://github.com/SysBioChalmers/RAVEN/tree/raven2.

Thanks for your interest in RAVEN!
