### ISSUE TITLE
help: getKEGGModelForOrganism invalid organism ID and HMM source

### ISSUE THREAD

**Issue by bardia510** [SysBioChalmers/RAVEN#342]
Hi,
I am trying to make a model for a bacterium by RAVEN Toolbox but when I used getKEGGModelForOrganism(organismID) the draft showed only 110 Rxns! so I tried to use Protein Fastafile to get a better result but I faced to some errors. 
I downloaded "prok100_kegg91" manually and used the command below:
model=getKEGGModelForOrganism('organism_id','fasta.csin.faa','prok100_kegg91')

These error appeared:
Error using dispEM (line 47)
The file 'genes.pep' cannot be located at prok100_kegg91/ and should be downloaded from the KEGG FTP.

Error in getKEGGModelForOrganism (line 561)
        dispEM(EM);

Then I changed the command:
model=getKEGGModelForOrganism('organism_id','fasta.cs.faa', 'c:\Documents\prok100_kegg91')

but enexpectedly I faced to another error:

Error using getKEGGModelForOrganism (line 363)
Fatal error occured. See the details above

I wonder if you could help me to make the model. 

By the way, when I make the model by getMetaCycModelForOrganism the draft show 750 Rxns. 

Thank you so much for your time and consideration. I look forward hearing from you.

Best regards

#### System information
* Please report:
1. RAVEN version : 2.4.3 
2. Operating system : Windows 7

**Comment by simas232** [comment]
@bardia510, welcome to GitHub and RAVEN repository. When reporting a new issue in the RAVEN repository, it is essential to include an entire issue template (only the lines starting with the asterisk symbol (*) should be removed). One does not need to comply with all three requirements given at the bottom of the template, but following [the guidelines to install RAVEN](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) is a must as this allows us to help to trace the problem quicker. Please do so and let us know what output you get when running `checkInstallation`. You may also consider running MATLAB in Administrator's mode since you use Windows 7.

My quick guess here is that some external binaries may be broken in Windows 7, but let's see what output you get from `checkInstallation`. Regarding reconstruction from KEGG, you are using RAVEN 2.4.3, so you should download [prok100_kegg94](https://chalmersuniversity.box.com/shared/static/swtz5pk6fuuo3e66itijl513vynrtlge), not prok100_kegg91 as this RAVEN version is compatible only with KEGG Release 94.

@ckitti, could you please have a check on the prok100_kegg94 download link? I see that it is currently dead, could be just a temporary issue.

**Comment by bardia510** [comment]
Dear @simas232 Thank you very very much for your prompt reply! I am sorry about I didn't follow the template.

I actually tried to download the latest version of Prok100_legg91 but the download link was broken. 

I ran "checkInstallation" and the result was:

*** THE RAVEN TOOLBOX v.2.4.3 ***

Checking if RAVEN is on the MATLAB path...									OK
Checking if it is possible to parse a model in Microsoft Excel format...	OK
Checking if it is possible to import an SBML model using libSBML...			OK
Solver found in preferences... none
Checking if it is possible to solve an LP problem using gurobi...			Not OK
Checking if it is possible to solve an LP problem using cobra...			OK
Preferred solver... NEW
Solver saved as preference... cobra

Checking essential binary executables:
NOTE: Broken binary executables must be fixed before running RAVEN
	makeblastdb.exe...							OK
	blastp.exe...								OK
	diamond.exe...								OK
	hmmsearch.exe...							OK
Checking non-essential/development binary executables:
NOTE: Only fix these binaries if planning to use KEGG FTP dump files in getKEGGModelForOrganism
	cd-hit.exe...								OK
	mafft.bat...								Not OK! If necessary, download/compile the binary and run checkInstallation again
	hmmbuild.exe...								OK

Checking whether RAVEN functions are non-redundant across MATLAB path...	Not OK
WARNING: Duplicate functions in C:\Users\user\cobratoolbox\src\reconstruction\comparison: 
    'compareModels.m'

It is strongly recommended to resolve conflicting functions as this may compromise RAVEN functionality

*** checkInstallation complete ***

Thank you very much for your kind help.

**Comment by edkerk** [comment]
@simas232 Note that the link to `prok100_kegg*` that you posted actually pointed to version 91 and is therefore no longer online. `prok100_kegg94` is [here](https://chalmersuniversity.box.com/shared/static/3h8a21cjc0mifj9mqrwlpdoxq8g6u02d) and functional, this link was also changed in [`getKEGGModelForOrganism`](https://github.com/SysBioChalmers/RAVEN/commit/63adb7498b14632bd4e2aa17ac37ea386bcd4679#diff-4f4f8da856e0f64f1be71e12d57db2aa4f18d560a966d6bea5825ef6ec9c585e).

**Comment by bardia510** [comment]
@edkerk 
Hi, Thank you for sharing the link but as @simas232 told me I need Prok100_kegg94 but when I click at the link you shared, Prok100_kegg91 would downloaded. 

I wonder if you could share the download link of Prok100_kegg94.

Thanks

**Comment by simas232** [comment]
@bardia510, I updated the download links for HMM sets including prok100_kegg94 in RAVEN Wiki. Please use [the following link](https://chalmersuniversity.box.com/shared/static/azpn5lwrb4gind2mn5hnbmux0lao5vt5) to download it.

HMMER seems to be working fine in your machine, let's see what draft model can you get when using prok100_kegg94. It may take up to 1 hour in Windows to fully run `getKEGGModelForOrganism`.

**Comment by bardia510** [comment]
@simas232 Thank you so much for your help!
I will run the function and let you know.

Best regards

**Comment by bardia510** [comment]
@simas232 
Hi, I ran the function but I faced to another error again. could you please tell me what the problem is?

Here is the results after running the function:

Downloading the HMMs archive file... COMPLETE
*** The model reconstruction from KEGG based on the protein homology search against KEGG Orthology specific HMMs ***

NOTE: Found prok100_kegg94 directory with pre-trained HMMs, it will therefore be used during reconstruction
Importing the global KEGG model from C:/Users/user/Documents/RAVEN-master/RAVEN-master/external/kegg/keggModel.mat... COMPLETE
Removing non-spontaneous reactions without GPR rules... COMPLETE
Fixing gene names in the model... COMPLETE
Importing the KEGG phylogenetic distance matrix from C:/Users/user/Documents/RAVEN-master/RAVEN-master/external/kegg/keggPhylDist.mat... COMPLETE

Error using dispEM (line 47)
The file 'genes.pep' cannot be located at prok100_kegg94/ and should be downloaded from the KEGG FTP.

Error in getKEGGModelForOrganism (line 561)
        dispEM(EM);

Thank you very much for your help!

**Comment by simas232** [comment]
@bardia510, this error means that the pre-trained HMM set is incomplete or cannot be recognized by RAVEN. Could you please include the prok100_kegg94 folder and your FASTA file in the same directory ar run the reconstruction again with the following settings:

 `model=getKEGGModelForOrganism('organism_id','fasta.csin.faa','prok100_kegg94')`;

If the error persists, try to reset MATLAB pathlist, do a clean reinstall of RAVEN and try again.

**Comment by simas232** [comment]
You may also try to put your working files in Desktop, not in Documents as this may also be an issue of Windows security.

**Comment by edkerk** [comment]
Before the reinstall of RAVEN, you may try to just remove the `prok100_kegg94` folder and the ZIP file before downloading it again. It might have been interrupted during download or ZIP extraction.
