### ISSUE TITLE
help: many errors when running in MATLAB trial version

### ISSUE THREAD

**Issue by Preshita1997** [SysBioChalmers/RAVEN#345]
I have one few problems while using RAVENTOOLBOX. I have installed MATLAB trial version R2021a and RAVEN Version 2.5.0 and branch master and getmodel homology ( I have tried both). Now I able to run tutorials available  in RAVEN toolbox successfully along with few function (codes) but majority of codes available in core file, external file, doc files are showing error while executing. One example is when I executed the function :  blastStructure=getBlast(organismID,fastaFile,modelIDs,refFastaFiles), it is showing this error  getBlast Not enough input arguments.  Error in getBlast (line 34) organismID=cellstr(organismID); I am receiving this kind of errors in many files and not able to perform functions. Please guide me for the same so that I can execute all programs available. Thank you.

**Comment by simas232** [comment]
RAVEN is not compatible with MATLAB trial versions, try full version

**Comment by edkerk** [comment]
@simas232 Why is does trial version not work?
@Preshita1997 How did you define `fastaFile` as part of the `blastStructure = getBlast(organismID, fastaFile, modelIDs, refFastaFiles)` command? Is it a string? I can only replicate this error if I do not specify the fastafile (so run `getBlast(organismID)` where `organismID = 'test'`). Can you please also post the output from `checkInstallation`?

**Comment by simas232** [comment]
@edkerk, I remember that several students had problems running RAVEN on the MATLAB trial version during the Metabolic Engineering course. That was back in autumn 2018-2019, not sure if this problem is still relevant. If I recall correctly, the Excel import function did not work, but I am not sure about the model reconstruction function, perhaps it worked well.

**Comment by Preshita1997** [comment]
Please find the attached screenshot of my matlab window. It seems there is
some error in a few lines and there are suggestions for adding percolating
arrays. Please help me solve this if possible.

**Comment by edkerk** [comment]
@Preshita1997 Screenshot is missing in your reply.

**Comment by Preshita1997** [comment]
Respected sir,
Please find the attached screenshot and help me rectify the same.
Apologies for the late reply.

Thank you,
Preshita Bhatt

**Comment by edkerk** [comment]
@Preshita1997 You should leave the comment + screenshot in GitHub, instead of replying via email. The screenshot is still missing.

**Comment by Preshita1997** [comment]
Respected sir,
Please find the attached screenshot and help me rectify the same.
Thank you.
![Screenshot (415)](https://user-images.githubusercontent.com/84510527/120474164-80b12a00-c3c5-11eb-86d3-0806298bddaf.png)

**Comment by edkerk** [comment]
You have changed the file `getBlastFromExcel`, line 1 is not `function 0` but rather `function blastStructure=getBlastFromExcel(models,blastFile,organismId)`. Probably best to remove the `RAVEN-master` folder and again unzip the file you downloaded from the RAVEN GitHub repository.
