### ISSUE TITLE
help: fillGaps function

### ISSUE THREAD

**Issue by mcesur1991** [SysBioChalmers/RAVEN#346]
Dear Sir/Madam,

I have reconstructed a genome-scale metabolic network model using an orthology-based approach. However, "cofactors and vitamins" in the biomass equation could not be produced. Therefore, I am trying gap-filling to add the lacking reactions. 

To this aim, I defined biomass formation reaction as the objective function for both template and draft models. To allow the addition of growth-related reactions via _fillGaps_ function, I set the lower bound of the biomass formation reaction in draft model to 1e-4. Then, I removed "genes" and "rxnGeneMat" fields from the template model. After performing gap-filling, I removed duplicate reactions using _checkDuplicateRxn_ function. Despite the addition of several reactions via _fillGaps_, there is no biomass formation even after gap-filling. 
**I used the following syntax:**
[newConnected, cannotConnect, addedRxns, balancedModel, exitFlag] = fillGaps(dmelGEM1, human_model, true, true, false, []);
**dmelGEM1: draft model and human_model: template model**

I would greatly appreciate if you could provide your comments or suggestions.
Thank you so much for your time and consideration.

Best Regards,
Müberra

**Comment by edkerk** [comment]
Welcome to RAVEN! To help you, it would be good to find out the following information:
- RAVEN version: `...`
- MATLAB version: `...`
- Solver selected: `...`
- Template model: `...`
I assume that the template model used for gap-filling is the same as the one used to generate the draft model?
What happens if you solve `balancedModel` before removing duplicate reactions?

**Comment by mcesur1991** [comment]
As you highlighted, the problem was related to the removed reactions. I manually checked these reactions and solved the problem. 
Thank you so much for your prompt feedback.

Best Regards,
