### ISSUE TITLE
CheckInstallation summary run through

### ISSUE THREAD

**Issue by joelmhaske** [SysBioChalmers/RAVEN#354]
### Description of the issue:

Hi, this is the first time using RAVEN 2.0, I have followed the installation steps so far, the latest step covered is installation of guribo solver, run the command setRavenSolver and finally check installation. Following is the output, could you please guide as to what needs to be fixed still, as I can see still few status as NOT OK, I'm not completely sure of the stepst to fix them. Please check below:

`
>> checkInstallation

*** THE RAVEN TOOLBOX v.2.5.1 ***

Checking if RAVEN is on the MATLAB path...									OK
Checking if it is possible to parse a model in Microsoft Excel format...	OK
Checking if it is possible to import an SBML model using libSBML...			The model contains 0 errors and 1 warnings.

OK
Solver found in preferences... gurobi
Checking if it is possible to solve an LP problem using gurobi...			Not OK
Checking if it is possible to solve an LP problem using cobra...			Not OK
WARNING: No working solver was found!
Install the solver, set it using setRavenSolver('solverName') and run checkInstallation again
Available solverName options are 'mosek', 'gurobi' and 'cobra'

Checking essential binary executables:
NOTE: Broken binary executables must be fixed before running RAVEN
	makeblastdb...							OK
	blastp...								OK
	diamond...								OK
	hmmsearch...							OK
Checking non-essential/development binary executables:
NOTE: Only fix these binaries if planning to use KEGG FTP dump files in getKEGGModelForOrganism
	cd-hit...								Not OK! If necessary, download/compile the binary and run checkInstallation again
	mafft.bat...								OK
	hmmbuild...								OK

Checking whether RAVEN functions are non-redundant across MATLAB path...	Not OK
WARNING: Duplicate functions in /home/joe/RAVEN/cobratoolbox/src/reconstruction/comparison: 
    {'compareModels.m'}

It is strongly recommended to resolve conflicting functions as this may compromise RAVEN functionality

*** checkInstallation complete ***`

Kind Regards,
Joel

**Comment by Hao-Chalmers** [comment]
@joelmhaske welcome to RAVEN. To better help you, we'd like to know what specifically do you expected from RAVEN, GEM reconstruction or FBA analysis?

**Comment by joelmhaske** [comment]
Hi Hao, My main focus at present is to use RAVEN for metabolic network reconstructions for hundreds of strains. I haven't decided yet about FBA analysis.

Thanks,
Kind Regards,
Joel

**Comment by Hao-Chalmers** [comment]
> My main focus at present is to use RAVEN for metabolic network reconstructions for hundreds of strains

Then you probably just move on to the reconstructions. RAVEN currently provides [getKEGGModelForOrganism](https://github.com/SysBioChalmers/RAVEN/blob/master/external/kegg/getKEGGModelForOrganism.m) and [getMetaCycModelForOrganism](https://github.com/SysBioChalmers/RAVEN/blob/master/external/metacyc/getMetaCycModelForOrganism.m) reconstruction functions that use KEGG and MetaCyc databases, respectively.

**Comment by joelmhaske** [comment]
Okay thanks. Does that mean that the few "NOT OK" warnings from the checkInstallation test command wouldn't hamper the quality of reconstructions I'd be looking for?

**Comment by simas232** [comment]
@joelmhaske, if you plan to use `compareModels` then you need to be extra careful. On the other hand, models should be curated manually afterward anyway, so this should not give any problems during reconstruction.

**Comment by Hao-Chalmers** [comment]
The two "NOT OK" about gurobi and cobra solvers indicates that you cannot run FBA, which wouldn't affect reconstructions.

**Comment by glucksfall** [comment]
Hello everyone,

I'm not a developer of RAVEN, just installed it today to use, so for future references:

Checking if it is possible to solve an LP problem using gurobi...:
- Install gurobi and add to the path GUROBI_PATH/linux64/matlab (change linux64 for the relevant directory in your SO)

Checking if it is possible to solve an LP problem using cobra...:
- Install cobratoolbox and add to the path the installation directory. Run initCobraToolbox before checkInstallation. The `compareModels.m` from cobratoolbox and from RAVEN will clash.

Checking non-essential/development binary executables:
- cd-hit: the binary in ravenDir/software/cd-hit is somehow broken, at least under linux:

```
$ ./cd-hit
bash: ./cd-hit: No such file or directory
```

You could manually edit files to use cd-hit from the path (e.g., `[res,~]=system(['"' fullfile(ravenDir,'software','cd-hit',['cd-hit' binEnd]) '"']);` to `[res,~]=system('cd-hit');`), however, I don't know how many files you need to modify to reflect that change in the pipeline.

Best!

**Comment by simas232** [comment]
@glucksfall, thank you for the useful tips! For the sake of readability, I changed the formatting of your post a little bit. I think RAVEN Wiki already covers the installation issues comprehensively but it is always good to check these instructions again and consider implementing the tips you pointed out.

Could you please specify which Linux distribution and version are you using? Even though `cd-hit` is considered more for development purposes, it would be great to fix this issue asap.

**Comment by glucksfall** [comment]
Hi @simas232,

Thanks for your reply. Actually, I came to the issues looking for if people already asked about that weird issue regarding `cd-hit`. So, I thought it would be helpful to add information to the original question. Just if others as me, don't read the Wiki.

BTW, I use Ubuntu 20.04.

Best!

**Comment by edkerk** [comment]
Since release v2.6.0, the output from `checkInstallation()` has changed:

```matlab
*** THE RAVEN TOOLBOX v.2.6.0 ***

MATLAB R2021a detected

Checking if RAVEN is on the MATLAB path...									OK
Checking if it is possible to parse a model in Microsoft Excel format...	OK
Checking if it is possible to import an SBML model using libSBML...			The model contains 0 errors and 1 warnings.

OK
Solver found in preferences... gurobi
Checking if it is possible to solve an LP problem using gurobi...			OK
Checking if it is possible to solve an LP problem using cobra...			Not OK
Preferred solver... KEPT
Solver saved as preference... gurobi

Checking essential binary executables:
	BLAST+... OK
	DIAMOND... OK
	HMMER... OK
Checking whether RAVEN functions are non-redundant across MATLAB path...	OK

*** checkInstallation complete ***
```

CD-HIT and MAFFT binaries are only tested if `checkInstallation(true)` is run.
