### ISSUE TITLE
help: getKEGGModelForOrganism download pre-trained HMMs

### ISSUE THREAD

**Issue by bapimandal** [SysBioChalmers/RAVEN#36]
While following the RAVEN tutorial I was unable to download the model from KEGG through 'ftp'. Each time it throws an error like :
 
>> "/pub/kegg/ligand/compound/" is nonexistent or not a directory.
 
I would be very glad if someone could show me a way around to fix the issue.

Thanks,
Bapi Mandal.

**Comment by simas232** [comment]
Hi @bapimandal ,

Could you try to download [the latest RAVEN version](https://github.com/SysBioChalmers/RAVEN/releases/tag/v2.0.0-rc.1) and start over? The latest release should fix your issue.

**Comment by bapimandal** [comment]
Hello @simas232 

I tried with the latest version and this time I got a different error:
'The file 'genes.pep' cannot be located at euk100_kegg82/ and should be downloaded from the KEGG FTP.'

Also I would like to know whether or not can this script getKEGGModelforOrganism be used for my any organism present in the KEGG.

**Comment by edkerk** [comment]
1. Can you please specify what command you are exactly running? Tutorial4.m specifies:

`model=getKEGGModelForOrganism('sce','sce.fa','euk100_kegg82','output',false,false,false,10^-30,0.8,0.3,-1);
`

and this command should work when in the `tutorial` folder (you can check this with `pwd`).

2. Perhaps something went wrong with downloading the HMMs. Try to remove the euk100_kegg82 folder with `rmdir('euk100_kegg82', 's')` and rerun the command from the tutorial.

3. This function can make model based on two inputs (also see the [getKEGGModelForOrganism](../blob/master/external/kegg/getKEGGModelForOrganism.m)  documentation):

- Only provide 3-4 letter KEGG organism abbreviation as 'organismID' parameter will generate a model according to KEGG annotated reactions. This works for _any_ organism in KEGG, as long as a valid organism abbrevation is given (see http://www.genome.jp/kegg/catalog/org_list.html).

- If you provide a protein fasta of your organism of interest, it will do the HMM search based on KEGG annotations, and this should work for _any_ organism, irrespective of whether they are in KEGG or not.

**Comment by simas232** [comment]
Yes, you can definitely use RAVEN to reconstruct model from KEGG as this is the one of the key RAVEN features. Although KEGG FTP access is not freely available, RAVEN contains reformatted KEGG reactome database with KO (KEGG Orthology) associations in MAT format. This means that for the model reconstruction from KEGG the user does not need to have KEGG FTP subscription. We update MAT files once per year, usually in spring. The current KEGG version bundled in RAVEN is from spring 2017.

Regarding the model reconstruction pipeline from KEGG, please check the @edkerk answer, point 3.

**Comment by zhxiaokang** [comment]
Hi, we got similar error while using the function getKEGGModelForOrganism: 
```
Error using fprintf
Invalid file identifier.  Use fopen to generate a valid file identifier.

Error in getKEGGModelForOrganism (line 537)
        EM=fprintf(['The file ''genes.pep'' cannot be located at ' strrep(dataDir,'\','/') '/
        and should be downloaded from the KEGG FTP.\n']);
```
We followed the answer from @edkerk but still couldn't figure it out. But we don't understand: we only created an empty folder called "euk90_kegg87", then we set the function running, so we're expecting the function to create the folder "fasta" and also the inside file "genes.pep" by itself. Is that understanding correct? If yes, why does it require us to download it from KEGG FTP?

**Comment by edkerk** [comment]
@zhxiaokang 
Can you please provide the exact commands that you run, all output that is generated, and the RAVEN version you're using?

You are not supposed to create an empty folder called "euk90_kegg87", `getKEGGModelForOrganism` will generate this folder by downloading pre-trainedHMMs from our server.

If it does not find pre-trained HMMs, the function will try to train HMMs. For this is needs to use FASTA files and the genes.pep that can be downloaded from KEGG FTP. As long as you use the pre-trained HMMs, you don't need these fasta or genes.pep files.

So something seems to be going wrong with downloading the pre-trained HMMs. If you post the full input and output we can try to figure out why.

**Comment by zhxiaokang** [comment]
I'm using the version 2.1.0, but using the master branch. I just tried switching to the branch devel, and retried what I did. But got new errors. So currently, the command is:
`zf = getKEGGModelForOrganism("dre", "trinity_list3amino_blastbased.fasta","euk100_kegg87", "out", true, true, true, false)`
But I got this error:
```
Error using exist
The first input to exist must be a string scalar or character vector.

Error in getKEGGModelForOrganism (line 371)
        elseif ~exist(dataDir,'dir') && exist([dataDir,'.zip'],'file')
```

If I create this folder "euk100_kegg87" before I ran the command, and reran the same command, I got another error:
```
Provided dataDir is in correct format for this RAVEN version in order to use pre-trained HMMs...
  Columns 1 through 4

    "The HMM files see…"    "euk100_kegg87"    "/hmms. Please rem…"    "euk100_kegg87"

  Column 5

    " folder and rerun…"

Error using getKEGGModelForOrganism (line 386)
Fatal error occured. See the details above
``` 

BTW, there are 2 bugs: "isstr" in line 283 and 322 should be "isstring", otherwise, I got this error:
```
Error using getKEGGModelForOrganism (line 284)
outDir should be provided as string
```

**Comment by edkerk** [comment]
In MATLAB one uses `´` to indicate strings, not `"`. So please change this when calling `getKEGGModelForOrganism` and any other function in RAVEN.

Again, do *NOT* manually create `euk100_kegg87` folder.

Please *DO* try the `devel` branch for this function, as it has been modified to correct bugs present in the `master` branch.

Finally, what version of Matlab are you using?

**Comment by zhxiaokang** [comment]
Thank you! Never thought of the issue of `"`... Problem solved now. It's Matlab R2018a on Mac.

**Comment by yingzhang001** [comment]
While following the RAVEN tutorial I was unable to download the model from KEGG . Each time it throws an error like :
Downloading the HMMs archive file... 错误使用 websave (第 98 行)
指向 URL
'https://chalmersuniversity.app.box.com/public/static/j19ybilr7js34uisnss92gvq5g6lljkk.zip'
的连接在 5.000 秒后超时。原因是 "Failed to connect to
chalmersuniversity.app.box.com port 443: Operation timed out"。可能服
务器没有响应，或者 weboptions.Timeout 需要设置为更高的值。

**Comment by yingzhang001** [comment]
the command is:DW2KeggDraftModel=getKEGGModelForOrganism('DW2','DW2.faa','prok90_kegg94','out',true,true,true,false)
but I got this error:
Downloading the HMMs archive file... Incorrect use of websave (line 98)
 point tonURL
'https://chalmersuniversity.app.box.com/public/static/j19ybilr7js34uisnss92gvq5g6lljkk.zip'
The connection timed out after 5.000 seconds. The reason is "Failed to connect to
chalmersuniversity.app.box.com port 443: Operation timed out"。
line 378
websave([dataDir,'.zip'],['https://chalmersuniversity.box.com/shared/static/',hmmLinks{hmmIndex},'.zip']);

**Comment by edkerk** [comment]
Please update to the latest [release](https://github.com/SysBioChalmers/RAVEN/releases), as the HMMs are distributed differently since RAVEN 2.6.0.

Also please note that the KEGG version was updated, so you should use `prok90_kegg100` as parameter when running `getKEGGModelForOrganism`

**Comment by ericamanga** [comment]
Hello,

I was obtaining one model from KEGG without homology and got an error while running with my fasta file. Then I tryied to run the tutorial5 available in RAVEN 2.5.12, and I got this error:

```
>> model=getKEGGModelForOrganism('sce','sce.fa','euk90_kegg100','output',false,false,false,false,10^-30,0.8,0.3,-1);

*** The model reconstruction from KEGG based on the protein homology search against KEGG Orthology specific HMMs ***

Error using getKEGGModelForOrganism (line 328)
Pre-trained HMMs set is not recognised. If you want download RAVEN provided sets, it should match any of the following: euk90_kegg102 or prok90_kegg102
```

When I went to download the Pre-Trained Hidden Markov Models euk90_kegg102 in github <https://github.com/SysBioChalmers/RAVEN/wiki/Use-Pre-Trained-HMMs> I did not find anyone with a matched name (euk90_kegg102). Am I looking for it in a wrong link?

How could you suggest me to keep with this reconstruction? Thank you since now.

**Comment by ericamanga** [comment]
Thank you, I'm gonna try again! But sorry, I wrote it wrongly, my current version of RAVEN is 2.7.12 (instead of 2.5.12). Thus, all my error messages corresponded to RAVEN 2.7.12!

**Comment by edkerk** [comment]
RAVEN 2.8.0 is now released, where `'euk90_kegg105'` as input for `getKEGGModelForOrganism` should work. If you encounters problems with that version, please feel free to open a [new Issue](https://github.com/SysBioChalmers/RAVEN/issues/new) here on GitHub!

**Comment by ericamanga** [comment]
Dear @edkerk,
Great to have a new release! I got the following error messages:

```
>> model=getKEGGModelForOrganism('sce','sce.fa','euk90_kegg105','output',false,false,false,false,10^-30,0.8,0.3,-1);

*** The model reconstruction from KEGG based on the protein homology search against KEGG Orthology specific HMMs ***

Undefined function 'isfile' for input arguments of type 'char'.

Error in checkFileExistence (line 57)
        if ~isfile(files{i})

Error in getKEGGModelForOrganism (line 303)
    fastaFile=checkFileExistence(fastaFile,2); %Copy file to temp dir
```
 
And also in checkInstallation:

```
>> checkInstallation

*** THE RAVEN TOOLBOX ***

 > Installing from location             /home/erica/Documents/RAVEN-2.8.0
 > Checking RAVEN release               2.8.0
   > You are running the latest RAVEN release
 > Checking MATLAB release              2017a
 > Checking system architecture         glnxa64
 > Set RAVEN in MATLAB path             Pass
 > Save MATLAB path                     Pass
   > Make binaries executable           Undefined function 'isfile' for input arguments of type 'char'.

Error in findRAVENroot (line 13)
    isRoot = isfile(fullfile(ravenPath,'RAVEN2.png'));

Error in checkInstallation>makeBinaryExecutable (line 297)
binDir = fullfile(findRAVENroot(),'software');

Error in checkInstallation (line 88)
    status = makeBinaryExecutable();
 
```

Best,

**Comment by edkerk** [comment]
Ok, this is because you use MATLAB 2017a, while the function `isfile` was introduced from version 2017b. Would you have the change to install a more recent MATLAB installation? Otherwise I can tweak the code to avoid the use of this function.

**Comment by ericamanga** [comment]
Hi @edkerk I could not install the latest version of MATLAB 2023a (still trying, likely a linux issue). Then I wonder whether you could tweak the code...

**Comment by edkerk** [comment]
@ericamanga, you may try the [`pre-matlab2017b`](https://github.com/SysBioChalmers/RAVEN/tree/pre-matlab2017b) branch, where the use of `isfile` and `isfolder` is avoided.

- If you use Git to get the RAVEN code, just check-out the `pre-matlab2017b` branch
- Otherwise download [this ZIP](https://github.com/SysBioChalmers/RAVEN/archive/refs/heads/pre-matlab2017b.zip) and use it to replace your current RAVEN installation.

If you encounter any problems, related to the above or anything else with RAVEN, please open a **[new Issue](https://github.com/SysBioChalmers/RAVEN/issues/new)** on GitHub.
