### ISSUE TITLE
unintended prefix for compartment i

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/RAVEN#366]
### Description of the issue:
When exporting Human-GEM from `yml` to `xml`, the compartment `i` becomes `c_i`. It is the only compartment that gets prefixed with `c_`. The root cause is likely in the lines https://github.com/SysBioChalmers/RAVEN/blob/800362e71b9d04ae2e2a16960b9d19aff346d37e/io/exportModel.m#L224-L231
Maybe due to the unintended interpretation of i as an [imaginary unit](https://en.wikipedia.org/wiki/Imaginary_unit)?

#### Reproducing this issue:
Below is a test case that demonstrates the bug:
```matlab
compartment = 'i';
if ~isnan(str2double(compartment))
compartment=strcat('c_',compartment);
end
disp(compartment)
```
```
c_i
```

#### System information
The bug is based on the latest release of RAVEN, demonstrated above in Matlab 2019b on macOS.

**I hereby confirm that I have:**
- [ ] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by edkerk** [comment]
You're right. Checking whether something is numeric using `str2double` is very sloppy, this is fixed by changing line 225 as:

```matlab
        if any(regexp(model.comps(i),'^\d'))
```

Will make a PR for this asap. Meanwhile, `exportModel` from #360, together with the extended `checkModelStruct` from #353 would prevent these issues.

**Comment by mihai-sysbio** [comment]
> Will make a PR for this asap. Meanwhile, `exportModel` from #360, together with the extended `checkModelStruct` from #353 would prevent these issues.

Thanks @edkerk for the quick action.
