### ISSUE TITLE
feat: use SBML GEMs in the pipeline based on tutorial6

### ISSUE THREAD

**Issue by joel8484** [SysBioChalmers/RAVEN#370]
### Description of the issue:
Hi I wanted to create and compare a combined GEM with a previously existing model which is in .sbml format. As I saw in the tutorial, a reconstruction in .mat format has been loaded as an input. I just wanted to ask whether the same functions will run if I load a model in .sbml format as well? 
*Try to be as clear as possible, e.g.:
- Is there a functionality missing? No functions missing. Just need clarity on the file format compatibility to use in comparison of newly created combined model and an existing draft model
- Did an existing function fail? - yes. tutorial 6 line 91.
- What is the exact error message, and other output that you got? `>> load('Actinomyces_oris_T14V.xml','selectedNewRxns');
Error using load
Unable to read file 'Actinomyces_oris_T14V.xml'. Input must be a MAT-file or an ASCII file containing numeric data with same number of columns
in each row.`
- What have you tried yourself to fix it? no. Since I did not have a reconstruction in .mat format

I would also like to add, that in the paper in table 1 it has shown that RAVEN accepts import file as SBML file. Does this apply here as well?

#### Reproducing this issue:
As pasted above
```

#### System information
* Please report:
1. RAVEN version RAVEN TOOLBOX v.2.5.1
2. Operating system Ubuntu 18.04.5

**I hereby confirm that I have:**
- [ X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X ] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by simas232** [comment]
@joel8484, yes, you can import GEMs in SBML format and use them in the `tutorial6` pipeline as well. Just use the `importModel` function instead of `load`. FYI, it is possible to export imported GEMs to `mat` format if needed.

I also see that you get an error in Line 91. The `selectedNewRxns` structure should only contain reactions that are found in the new GEM version. The purpose of this command is to load the list of these reactions, not the new model (iMK1208) itself.

**Comment by joel8484** [comment]
Hi Simonas, Okay I learn that the file obtained in tutorial 6 iMK1208+suppInfo.mat is done by manual curation. However, can I find a workflow of commands which can render which I will follow to get those? It would be very helpful. As I'm exploring the best use of RAVEN to get reconstructions for my project. I might have to ask few queries here and there with some new functionalities I will face along the way. I hope you understand.

Thanks for understanding and thanks for explaining all my queries in past few days.
Thanks very much,
Joel

**Comment by simas232** [comment]
You can find several relevant functions demonstrated in `tutorial5`. Before proceeding, you should first decide which one of those two models is the primary one. It is imperative that this model is functional, i.e. can predict growth in a given medium. This would be the model which you would then enrich with reactions from the other (secondary) model.

Might be a better idea not to immediately use the `mergeModels` function, but to add reactions from the secondary model in batches. The advantage of this approach is that if you get any model functionality issues, you would be able to identify the root of the problem quicker. However, if you decide to merge the models in the beginning, you would encounter all such problems at once and the whole-model manual curation would likely be necessary. I did this before myself and it was really not the most time-efficient solution.

Also, I would like to advise you to summarize all the manual curation steps in a script as this would allow to roll back the changes during the curation process and would even be useful for later uses.

**Comment by joel8484** [comment]
Hi Simonas,

Thanks perfect. One last query before closing this thread: Actually this is for tutorial 5 - after manual curation and running the entire template, the new model that is curated can be exported to my drive using exportModel(newModel, 'abc.faa.xml') and this should give me the curated model, is that correct?

Regards,
Joel

**Comment by simas232** [comment]
Yes, you can export the curated model back to SBML format with the `exportModel` function. Just try to only use dot symbols to separate the file format from the filename, not in the filename instead, to avoid confusion. In your example, the more appropriate full name for the model would be `abc_faa.xml`. 

FYI, RAVEN also supports non-conventional Excel format which can be exported from MATLAB using the `exportToExcelFormat` function and imported back to MATLAB with the `importExcelModel` function. The main advantage of the Excel format is that one can overview the model content in a much more convenient way. On the other hand, the final model version should be in SBML format anyway.

**Comment by joel8484** [comment]
Oh yeah. I was meaning to put an underscore in the file name; my naming convention was by mistake. Thanks, Simonas for your guidance. 
Regards,
Joel
