### ISSUE TITLE
gapreport

### ISSUE THREAD

**Issue by zahraazimzadeh** [SysBioChalmers/RAVEN#372]
### Description of the issue:
*Try to be as clear as possible, e.g.:
- Is there a functionality missing?
- Did an existing function fail? yes gapreport
- What is the exact error message, and other output that you got? Gap analysis for iMT1026v3 - Torres2019 - Contextualized P. pastoris GSMM under glucose growth and various oxygenation levels

Index exceeds the number of array elements (0).

Error in haveFlux (line 52)
J(abs(sol.x(mixIndexes))>cutOff)=true;

Error in gapReport (line 64)
I=haveFlux(model);
- What have you tried yourself to fix it? I tried the gapreport for the **small yeast mode**l in the tutorial folder and didn't get any error. Actually I want to check the latest model of pichia pastoris so I tried gapreport for the xml file of it. 

#### Reproducing this issue:
*If applicable, please attach the problematic code. 

model=importModel('iMT.xml',true,false,true);
   gapReport(model);

#### System information
* Please report:
1. RAVEN version (stabile [release](https://github.com/SysBioChalmers/RAVEN/releases), `devel` branch?) RAVEN 2
2. Operating system (Windows/Mac/Linux; include version) Windows

**I hereby confirm that I have:**
- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN. 
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

*Note: replace [ ] with [X] to check the box. PLEASE DELETE THIS LINE*

**Comment by edkerk** [comment]
This is solved in #408 ([`haveFlux`](https://github.com/SysBioChalmers/RAVEN/pull/408/files#diff-3b840c79146ea536035c599c49d0b9fc7728995c8f26dd300e72dbb7850b43c3)), but the underlying problem is probably that the model is not functional to start with (if this model is the same as the one downloaded from [BioModels](https://www.ebi.ac.uk/biomodels/MODEL1910040001#Files)).

**Comment by zahraazimzadeh** [comment]
👌
