### ISSUE TITLE
compareModels similar name as in cobratoolbox

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#375]
### Description of the issue:
There is a `compareModels` function in [RAVEN](https://github.com/SysBioChalmers/RAVEN/blob/master/core/compareModels.m), while a similarly named function exists in [COBRA](https://github.com/opencobra/cobratoolbox/blob/master/src/reconstruction/comparison/compareModels.m).

Also reported as part of #354.

`compareModels` in RAVEN is not called by any other functions and could safely be renamed. What should be the updated function name?
- `compareModelContent` (no, the function does not compare all model content, see the [function](https://github.com/SysBioChalmers/RAVEN/blob/master/core/compareModels.m).)
- ~~`compareMultipleModels` (okay?)~~
- `findModelOverlaps` (also okay?)
- `compareRxnsGenesMets`
- `compareRxnsGenesMetsComps`
- `...` (other suggestions?)

#### Reproducing this issue:
```matlab
>> checkFunctionUniqueness
Not OK
WARNING: Duplicate functions in C:\Work\GitHub\cobratoolbox\src\reconstruction\comparison: 
    {'compareModels.m'}

It is strongly recommended to resolve conflicting functions as this may compromise RAVEN functionality
```

#### System information
1. RAVEN 2.5.3
2. COBRA 3.33

**I hereby confirm that I have:**
- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by simas232** [comment]
Since there are no opinions from the others, I think it is okay if we rename `compareModels` into `compareRxnsGenesMetsComps`.
