### ISSUE TITLE
feat: migrate KEGG HMM sets from Box Sync to GitHub

### ISSUE THREAD

**Issue by simas232** [SysBioChalmers/RAVEN#376]
### Description of the issue:
KEGG HMM sets are currently stored in Box Sync. This was a great temporary solution for several years, but the time has come to deposit them somewhere else for simplified maintenance. I tested several options (Git LFS, external repository) and found a really elegant solution.

I suggest we manually include KEGG HMM zip archives as binary files in the current and future RAVEN releases. There is no need to have these attachments for every RAVEN version, but we should attach these archives as soon as we introduce the updated KEGG database in RAVEN. By doing this we will not need to incorporate KEGG HMMs into the RAVEN file structure and will not increase the overall size of the RAVEN repository (to my knowledge).

Please have a check at [this branch](https://github.com/SysBioChalmers/RAVEN/tree/test/checkKEGGHMMsRepo) to evaluate my suggested changes. I first created [my own repo](https://github.com/simas232/RAVEN.KEGG_HMMs) containing KEGG HMMs, but do not see the necessity to have a separate repository for them as we can include these zip files in RAVEN. If you give me a green light, I would attach KEGG HMM zip files to RAVEN 2.4.0 as this was the first version where we introduced KEGG Release 94.0.

Let me know your opinions @edkerk, @Hao-Chalmers, @mihai-sysbio, @JonathanRob

#### System information
RAVEN version: 2.5.3

**I hereby confirm that I have:**
- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by mihai-sysbio** [comment]
My suggestion would be to go ahead with Git LFS, since it is already used for this repository.

**Comment by simas232** [comment]
I did not know that Git LFS is used in this repository. Which files are traced?

Though, I am quite hesitant to use Git LFS to store KEGG HMMs since i) this forces users to download all 6 HMM sets; ii) there is a [monthly bandwidth quota of 1 GB](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage) that we would use very quickly and iii) this would require some unnecessary refactoring for KEGG reconstruction functions.

For now, I suggest that we try storing these KEGG HMMs in GitHub and if it does not work, we can always fall back to Git LFS.

**Comment by mihai-sysbio** [comment]
Let's not worry yet about (ii), I took care of it a while back and it still looks great
<img width="380" alt="image" src="https://user-images.githubusercontent.com/23480589/145871316-86ae2de0-d5fa-4d1d-9e3e-f2f90bfc4ca4.png">
I value the transparency (no one expects "new" stuff to be attached to a release), and simplicity (everything is fetched in the same command/action).
That being said, I don't oppose the conclusion, even though my preference is different.

**Comment by edkerk** [comment]
But there is no way of removing stuff from Git LFS, except from deleting the repo.

With the proposed solution, `getKEGGModelForOrganism` works as it's always done. Users won't manually download the HMM ZIP file from the `Release` view, it would be downloaded upon request by `getKEGGModelForOrganism`, it's just hosted on GitHub instead of on Box. As long as this is well documented in the SOP for updating the KEGG HMM ZIP files, then the user will never notice the difference.

**Comment by mihai-sysbio** [comment]
So how do we advance from here:
- should we create a PR straight-up from https://github.com/SysBioChalmers/RAVEN/compare/devel...test/checkKEGGHMMsRepo ? 
- should we document this change in the release process somewhere?

**Comment by simas232** [comment]
@mihai-sysbio, yes, we would create a PR from the branch you mentioned. Meanwhile, we would attach HMM sets to the RAVEN release in which KEGG Release 94 was introduced, because otherwise there is no way for us to check that the download links are working before releasing the new RAVEN version. Regarding the documentation of this change, I think that the description in the corresponding PR will be sufficient. In fact, RAVEN release notes have almost always been the collection of PR descriptions.
