### ISSUE TITLE
bug: exportModel writes invalid fluxObjective in SBML

### ISSUE THREAD

**Issue by OAshkar** [SysBioChalmers/RAVEN#380]
### Description of the issue:
- I created multiple tissue models using getINITModel2() function.  Then I exported those models in SBML format individually using the following command. 

```matlab
exportModel(Model,'models/context/heart.xml')
```
- Then, I have tried to use the R package piano to read these models _(please note that this is an R code)_
```R
piano::loadGSC("./models/context/heart.xml")
```
I got the following error:
```
Error : A <fluxObjective> object must have the required attributes 'fbc:reaction' and 'fbc:coefficient', and may have the optional attributes 'fbc:id' and 'fbc:name'. No other attributes from the SBML Level 3 Flux Balance Constraints namespace are permitted on a <fluxObjective> object.
Reference: L3V1 Fbc V2, Section 3.7
 Fbc attribute 'reaction' is missing.

Error in loadGSC("./models/context/heart.xml") : 
  file could not be read by rsbml_read()
```

#### System information
Operating system (Ubuntu 20.04)

**I hereby confirm that I have:**
- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by edkerk** [comment]
Just a check that an objective function was set for this model before export? `Model.rxns(Model.c))`

**Comment by edkerk** [comment]
Release v2.6.0 has more thorough check for presence of an objective function before model export, which should prevent this from happening.
