### ISSUE TITLE
setRavenSolver not working for Windows

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#4]
It is not possible to append the choice of RAVEN solver to the MATLAB startup in Windows. This is due to the following code:
```
	up=pathdef;
	up=regexp(up,':','split');
	up=up{1};
```
Running pathdef on my Matlab in Windows gives something that starts like 

> D:\Box Sync\Documents\MATLAB;D:\Box Sync\Documents\GitHub\cobratoolbox

So setRavenSolver then ends up trying to make a file at location

> D\startup.m

And this is of course an invalid location. I'm not sure where startup.m is supposed to be placed, so I can't suggest how to fix this for Windows.

Small comment, the error message you get from solveLP when no solver is set looks like this

> Raven solver not defined or unknown. Try using setRavenSolver("solver").

Probably best to swap " with '.

**Comment by zertan** [comment]
Changed the code to use the default user path for each os. May I ask you to do a git pull and see if it resolved the problem?

**Comment by edkerk** [comment]
It did not solve the problem. I know had some time to look at it myself, the main problem is with

> up=regexp(up,':','split');

which should be the following to make it work in Windows (in linux/mac, paths are separated by ':', in Windows it's by ';'

> if ispc
        up=regexp(up,';','split');
else
        up=regexp(up,':','split');

However, I now fixed it in my local branch by setting the solver as a Matlab preference. This seems to work very nicely, but I don't have permission to publish/push my branch to the remote.

**Comment by zertan** [comment]
You should now have write access. Push to your feature/bug fix branch and I will be happy to merge it! You can add "Fixes issue #2" to the commit message to automatically close this issue (once the branch is merged). //Daniel
