### ISSUE TITLE
help: Gurobi not found

### ISSUE THREAD

**Issue by isaacxdiaz** [SysBioChalmers/RAVEN#402]
### Description of the issue:

- Hi! I am trying to install RAVEN, followed Gurobi installation instruction and then proceeded to checkInstallation but doesn't seem to detect Gurobi WARNING: No working solver was found!, when trying the setRavenSolver(gurobi) I get the following error

```matlab
Error using gurobi
result = gurobi(model, params)
```

#### Reproducing this issue:

```matlab
*** THE RAVEN TOOLBOX v.2.6.0 ***

MATLAB R2021b detected

Checking if RAVEN is on the MATLAB path...									OK
Checking if it is possible to parse a model in Microsoft Excel format...	OK
Checking if it is possible to import an SBML model using libSBML...			The model contains 0 errors and 1 warnings.

OK
Solver found in preferences... gurobi
Checking if it is possible to solve an LP problem using gurobi...			Not OK
Checking if it is possible to solve an LP problem using cobra...			Not OK
WARNING: No working solver was found!
Install the solver, set it using setRavenSolver('solverName') and run checkInstallation again
Available solverName options are 'gurobi' and 'cobra'

Checking essential binary executables:
	BLAST+... OK
	DIAMOND... OK
	HMMER... OK
Checking whether RAVEN functions are non-redundant across MATLAB path...	OK

*** checkInstallation complete ***
```

#### System information
* Please report:
1. RAVEN version (stabile [THE RAVEN TOOLBOX v.2.6.0](https://github.com/SysBioChalmers/RAVEN/releases))
2. Operating system (MacOS 12.2.1)

**I hereby confirm that I have:**

- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by edkerk** [comment]
1. Could you please confirm your Gurobi version?

2. I assume you succesfully ran `gurobi_setup()`? Can you please show the output.

3. You mention an error when running `setRavenSolver`, but this is extremely unlikely, as it does not call Gurobi yet. Can you perhaps replicate the error message with the following code:
```matlab
setRavenSolver('gurobi')
load('empty.mat')
solveLP(emptyModel)
```

**Comment by isaacxdiaz** [comment]
>>>
Checked again this morning, checkInstallation command shows the expected output now! Probably it was an error of mine, apologies and thank you for helping!

```
*** THE RAVEN TOOLBOX v.2.6.0 ***

MATLAB R2021b detected

Checking if RAVEN is on the MATLAB path...									OK
Checking if it is possible to parse a model in Microsoft Excel format...	OK
Checking if it is possible to import an SBML model using libSBML...			The model contains 0 errors and 1 warnings.

OK
Solver found in preferences... gurobi
Checking if it is possible to solve an LP problem using gurobi...			OK
Checking if it is possible to solve an LP problem using cobra...			Not OK
Preferred solver... KEPT
Solver saved as preference... gurobi

Checking essential binary executables:
	BLAST+... OK
	DIAMOND... OK
	HMMER... OK
Checking whether RAVEN functions are non-redundant across MATLAB path...	OK

*** checkInstallation complete ***
```

```
setRavenSolver('gurobi')
load('empty.mat')
solveLP(emptyModel)

ans = 

  struct with fields:

       x: 0
       f: 0
    stat: 1
     msg: 'Optimal solution found'
```
