### ISSUE TITLE
Annotation problems + allow multiple subSystems

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#41]
RAVEN has two problems related to the annotation:
1. When importing yeast consensus model, the annotation is lost for reactions.
2. RAVEN doesn't function when specifying multiple subSystems for each reaction as cell array. See: SysBioChalmers/YeastMetabolicNetwork-GEM@03153ce79b7af9df71c8147eb8a8208ba1c86225.

- [x] importModel needs to be updated
- [x] exportModel needs to be updated
- [x] ravenCobraWrapper needs to be updated [@edkerk: no need, subSystems is identical in both model structures]
- [x] decide how subSystems are represented in Excel, as they need to be concatenated into one cell per reaction. Separated by ';'
- [x] exportToExcelFormat should be updated
- [x] exportToTabDelimited should be updated
- [x] confirm that functions modifying reactions can deal with cell arrays of subSystems, instead of strings
- [x] for the future update of KEGG mat files, we need to make sure that multiple subsystems are correctly imported. Many KEGG reactions belong to several subsystems and until now only the first mentioned subsystem was kept

**Comment by edkerk** [comment]
subSystems are no longer stored in modelSBML.reaction.notes, but in modelSBML.groups.

In importModel, should be parsed separately after looping through modelSBML.reaction (after line 650)

**Comment by simas232** [comment]
Regarding Excel format, I suggest we use semicolons to separate subSystems.

**Comment by edkerk** [comment]
importModel is now working: 53cc5daae9efa01c8d576c09acdab60c7cd85801, available from the [multiple_subSystems](https://github.com/SysBioChalmers/RAVEN/compare/multiple_subSystems) branch

**Comment by Hao-Chalmers** [comment]
This bug was report by whom, users or SysBio members?

**Comment by edkerk** [comment]
By me.

**Comment by edkerk** [comment]
Looking at the exportModel function now (to SBML). As mentioned above, subSystems will no longer be stored in modelSBML.reaction.notes, but in modelSBML.groups. Is this okay?

**Comment by simas232** [comment]
Yes, it is okay. It is nice that SBML does have native support for this, so there is no need to save it in notes field.

**Comment by edkerk** [comment]
exportModel now supports multiple subSystems as groups in the SBML file (commit f3add22fb877ae9470f0a77c2bc779db93ba818c and earlier).

From now on, the subSystems structure is a cell array, not string array.

**Comment by Hao-Chalmers** [comment]
By allowing the association of one reaction to multiple subSystems now and given that one subSystem always contains multiple reactions, a better representation of reaction-subSystem relationship would be a matrix (a natrual advantage of Matlab), which might be a better way than cell array.

**Comment by simas232** [comment]
We may implement this, but then we would make ravenCobraWrapper and possibly importModel, exportModel functions slower. I think that ravenCobraWrapper is slow enough already, so therefore suggest use subSystems field the way it is now.

I see that for gap filling and spontaneous reactions adding purposes it may be nice to have a function called getRxnsFromSubsystem. What do you think about such function?

**Comment by edkerk** [comment]
Good idea, but indeed let's keep subSystems as it is, and implement an additional function to construct such a matrix to be used by `getRxnsFromSubsystem` -like functionality.

**Comment by simas232** [comment]
All the mentioned issues are fixed now with in 6f29d82f24faceb6f80f7804edb04bf3ccb70209

**Comment by edkerk** [comment]
@tpfau Thanks for the tip! This functions works when model.subSystems is a structure of cell arrays? And does it work natively on RAVEN model structures? @simas232 If this function natively already supports RAVEN models, should we still include it (under a different name) in RAVEN?

**Comment by simas232** [comment]
@edkerk, model.subSystems are identical in RAVEN and COBRA, so yes, `findRxnsFromSubSystems` is natively compatible with RAVEN structure!

**Comment by tpfau** [comment]
It's up to you, I'm happy to create a PR with a different name (if you want), but I understand @simas232 argument, that it does not make a lot of sense to "just replicate" it.

**Comment by edkerk** [comment]
This is now pushed to master: #89
