### ISSUE TITLE
problematic use of RAVENSOLVER global in optimizeProb

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/RAVEN#425]
### Description of the issue:
The recent change to `optimizeProb` made [here](https://github.com/SysBioChalmers/RAVEN/commit/b1bc73bcf79b567dfaa9a49b0f2e9104cbcf5391#diff-404074c2d20a8002aa083b78fcc8bd52e673c048128b58183ecfb4995644fb9cR35-R40) uses a global variable `RAVENSOLVER` to determine which solver to use. However, once this function is run and the `RAVENSOLVER` global is set, the `setRavenSolver` function does not have any effect because it does not modify the `RAVENSOLVER` variable. Instead, to change the solver preference, the user must either manually set or clear the `RAVENSOLVER` global, or restart Matlab.

**I hereby confirm that I have:**
- [X] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)

**Comment by edkerk** [comment]
Background story: The idea behind this was to avoid having to run `getpref` with each run of `optimizeProb`, and querying a global variable `RAVENSOLVER` is much faster (~100x faster). However, global variables are not persistent (as you mention), while `setpref` is persistent even after MATLAB restart. We would want to avoid having to run something like `initCobraToolbox` (or RAVEN's `checkInstallation`) with each start-up.

Does #426 solve this?
