### ISSUE TITLE
There is an error in the old tINIT function (runtINIT) in the newest RAVEN version 

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/RAVEN#431]
### Description of the issue:
Line 286 is
prob.csense=char(1,zeros(size(prob.a,1)));
should have been
prob.csense=char(zeros(1,size(prob.a,1)));

The last minute fix was intended to just change the dimension in which the vector grows, but instead creates a strange matrix, which messes things up.
Could we get this fixed as soon as possible and merged into a new version, the old tINIT currently doesn't work as it should.

Simple mistake in a last minute fix.

RAVEN version 2.7.2
On Windows

**I hereby confirm that I have:**
- [X ] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [X] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by JonathanRob** [comment]
@johan-gson this is already fixed in `devel`.

**Comment by johan-gson** [comment]
ok, I'm closing this
