### ISSUE TITLE
findGeneDeletions can‘t work

### ISSUE THREAD

**Issue by ZhendongZhangSCAU** [SysBioChalmers/RAVEN#432]
Try to run FBA using `findGeneDeletions` ,but the issues occurred:

>> [genes, fluxes, originalGenes, details]=findGeneDeletions(model,'sgd','fba');

> Error using cellfun
> Input #2 expected to be a cell array, was double instead.
> 
> Error in convertCharArray (line 18)
>     elseif ~iscell(funcInput) && ~(all(cellfun(@ischar, funcInput)) || all(cellfun(@isstring,
>     funcInput)))
> 
> Error in removeGenes (line 41)
>     genesToRemove=convertCharArray(genesToRemove);

I wonder what is the "Input #2" and how I can solve this format problem which not just occurred in one model. 

thanks!🌹

**Comment by edkerk** [comment]
Will fix asap.

**Comment by edkerk** [comment]
I cannot replicate this error. When `findGeneDeletions` calls `removeGenes`, the `genesToRemove` is always a number, which means that line 41 will not run (as line 40 will be false). Did you make any changes to the code?

**Comment by edkerk** [comment]
How did you then load the model? The `mat` version? Just trying to replicate the error here. You should not have to convert any gene identifiers.

**Comment by edkerk** [comment]
Regarding the SBML file, the use of square brackets in the model name is what makes the file invalid:

`<model metaid="iNR1329" id="iNR1329" name="C. militaris GEM by Nachon Raethong [29-OCT-2019]" fbc:strict="true">`

Remove the square brackets `[` and `]` to get a model that can directly be loaded in RAVEN.

However, when I do this I do not get any error messages when running `findGeneDeletions`. Could you please report your OS and MATLAB version?

**Comment by ZhendongZhangSCAU** [comment]
I am able to load the model in the `mat` version, but when loading `xml ` version, issues occurred below:

> Error using dispEM (line 49)
> There is a problem with the SBML file. Try using the SBML Validator at
> http://sbml.org/Facilities/Validator
> 
> Error in importModel (line 141)
>     dispEM(EM);

After I removed the square brackets, problems still exist.

Well, I am working with Windows 10 and MATLAB R2019a.

**Comment by edkerk** [comment]
Please make sure you're using the [latest RAVEN release](https://github.com/SysBioChalmers/RAVEN/releases), I think the issue you're encountering with `findGeneDeletions` is due to a bug in `removeGenes` that was fixed in v2.7.2.

Regarding the XML file, did you use the same SBML file that I posted in my previous message?

**Comment by ZhendongZhangSCAU** [comment]
Well, after installing the [latest RAVEN release](https://github.com/SysBioChalmers/RAVEN/releases) (v2.7.5), I successfully run  FBA using `findGeneDeletions`!!

What's more, I can get the SBML model from the file you posted in previous message([model.xml](https://github.com/SysBioChalmers/RAVEN/files/9000397/model.zip)) using `importModel`!!

Thank you for your patience!🌹

**Comment by ZhendongZhangSCAU** [comment]
furtherly, I would like to know what changes have you made to this file([model.xml](https://github.com/SysBioChalmers/RAVEN/files/9000397/model.zip))?

since I can't read it by cobrapy due to the issuses below:

> 'SBML_WARNING': ['E0 (Warning): General SBML conformance (core, L3); RDF does not contain valid ModelHistory; LibSBML expected to read the annotation into a ModelHistory object. Unfortunately, some attributes were not present or correct and the resulting ModelHistory object will not correctly produce the annotation.  This functionality will be improved in later versions of libSBML. \nReference: L3V1 Section 6.3\n An invalid ModelHistory element has been stored.\n',
>    'E76 (Warning): General SBML conformance (core, L3); RDF does not contain valid ModelHistory; LibSBML expected to read the annotation into a ModelHistory object. Unfortunately, some attributes were not present or correct and the resulting ModelHistory object will not correctly produce the annotation.  This functionality will be improved in later versions of libSBML. \nReference: L3V1 Section 6.3\n An invalid ModelHistory element has been stored.\n'],
>   'COBRA_FATAL': ["id 'tetrahydrobiopterin' at index 1591 is non-unique. Is it present twice?"],
>   'COBRA_ERROR': [],
>   'COBRA_WARNING': [],
>   'COBRA_CHECK': []})

**Comment by ZhendongZhangSCAU** [comment]
or could you please try to read this by _COBRApy_ ?

[xml of iPC1469.zip](https://github.com/SysBioChalmers/RAVEN/files/9007411/xml.of.iPC1469.zip)

**Comment by ZhendongZhangSCAU** [comment]
Thank you again!

I am contacting with the authors.
