### ISSUE TITLE
The meaning of output parameters of FSEOF

### ISSUE THREAD

**Issue by ZhendongZhangSCAU** [SysBioChalmers/RAVEN#437]
After I ran FSEOF and exported a `xls` file, I get the vision below:

![1706ebafab91ab39748612e3bf8d698](https://user-images.githubusercontent.com/95110105/176612391-ec56a1cc-ad20-4034-b16f-2cd0c84ba1c3.png)

I wonder what's the meaning of the `slope` and `direction`

thank you!🌹

**Comment by ZhendongZhangSCAU** [comment]
well I see the answer in https://github.com/SysBioChalmers/RAVEN/issues/220

and now I want to know how to confirm the target genes(or what we say key genes)?
By the `Gr Rule`? all of the genes is the key gene to delete or overexpress?

**Comment by ZhendongZhangSCAU** [comment]
any good guys answer me?😥

**Comment by haowang-bioinfo** [comment]
> I wonder what's the meaning of the slope and direction

the FSEOF method explores reactions that are co-upregulated together with the one for target formation. The slope value indicates the times of flux change when assuming that the target formation flux has 1 unit of flux increase.

**Comment by ZhendongZhangSCAU** [comment]
thank you @haowang-bioinfo 

and now I want to know how to confirm the target genes(or what we say "key genes")?
By the `Gr Rule`? all of the genes are the key genes we can delete or overexpress?

**Comment by ZhendongZhangSCAU** [comment]
hello？

**Comment by JonathanRob** [comment]
@ZhendongZhangSCAU I don't think that the model/simulations will be able to tell you much more beyond which genes are of interest. Once you obtain the "key genes", then I would suspect that the next best step is to manually investigate the literature/gene databases for further biological details on these genes, and identify which genes should be targeted for deletion or overexpression in followup experiments.
