### ISSUE TITLE
bug: on Apple silicon CPU getDiamond fails

### ISSUE THREAD

**Issue by Soratake-HirotakaYajima** [SysBioChalmers/RAVEN#457]
### Description of the issue:

Hello everyone.
I use RAVEN-2.7.9 on MATLAB_R2021a, macOS 13.1

At tutorial 6, I got an error when I commanded ScoMetaCycDraftModel=getMetaCycModelForOrganism('ScoMetaCyc','Sco_all_protein.faa',1);

checkInstallation was passed
=== Essential binary executables ===
 > Checking BLAST+                      Pass
 > Checking DIAMOND                     Pass
 > Checking HMMER                       Pass

How do I fix it??

best wishes

----------
>> ScoMetaCycDraftModel=getMetaCycModelForOrganism('ScoMetaCyc','Sco_all_protein.faa',1);
Checking existence of query FASTA file... done
Importing MetaCyc reactions from metaCycRxns.mat... done
done
Reorganizing reaction-enzyme associations... done
Importing MetaCyc metabolites from metaCycMets.mat... done
The full MetaCyc model loaded
Running DIAMOND blastp with "MetaCyc" against "ScoMetaCyc"..
Checking existence of query FASTA file... done
Importing MetaCyc reactions from metaCycRxns.mat... done
done
Reorganizing reaction-enzyme associations... done
Importing MetaCyc metabolites from metaCycMets.mat... done
The full MetaCyc model loaded
Running DIAMOND blastp with "MetaCyc" against "ScoMetaCyc"..
"/Users/username/RAVEN-2.7.9/software/diamond/diamond.mac" blastp --query "/private/var/folders/vw/qvg0802d0jddk4tlq0hkzd8c0000gp/T/tpcc79a38e_bed0_4b8d_b7b7_7bab48df4937" --out "/private/var/folders/vw/qvg0802d0jddk4tlq0hkzd8c0000gp/T/tpa9168c25_6151_4fcb_a2f2_1daa2ab9e084_1" --db "/private/var/folders/vw/qvg0802d0jddk4tlq0hkzd8c0000gp/T/tpb5c6c7d9_f784_46f7_b7a7_a2418b1fbaff" --more-sensitive --outfmt 6 qseqid sseqid evalue pident length bitscore ppos --threads 8: Illegal instruction
ERROR: dispEM (line 49)
DIAMOND blastp did not run successfully, error: 132

ERROR getDiamond (line 118)
        dispEM(EM,true);

ERROR: getMetaCycModelForOrganism (line 92)
        blastStruc=getDiamond(organismID,fastaFile,{'MetaCyc'},fullfile(ravenPath,'external','metacyc','protseq.fsa')); 

#### Reproducing this issue:

```matlab
ScoMetaCycDraftModel=getMetaCycModelForOrganism('ScoMetaCyc','Sco_all_protein.faa',1);
```

#### System information
* Please report:
1. RAVEN version (stabile [release](https://github.com/SysBioChalmers/RAVEN/releases), `devel` branch?)
2. Operating system (Windows/Mac/Linux; include version)

**I hereby confirm that I have:**

- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by Soratake-HirotakaYajima** [comment]
=== Essential binary executables ===
 > Checking BLAST+                      Pass
 > Checking DIAMOND                     Pass
 > Checking HMMER                       Pass

**Comment by edkerk** [comment]
I do not have a Mac at hand to test (cannot replicate this error on Windows PC).

What type of Mac is it? (or most important: does it have M1/M2 or Intel CPU?)

**Comment by Soratake-HirotakaYajima** [comment]
it have M2 CPU.

**Comment by edkerk** [comment]
Ok, this makes me think it is a M2-related problem with DIAMOND, although it is surprising that it passed during `checkInstallation` (you could also run `runtests('diamondTests')` stand-alone).

I do not have access to M1/M2-Mac so a cannot further troubleshoot. As a workaround, you might want to try:

`model=getMetaCycModelForOrganism('ScoMetaCyc','Sco_all_protein.fa',1,0,0,100,45,false)`

where the flag indicates that getBlast should be used instead of getDiamond.

**Comment by Soratake-HirotakaYajima** [comment]
Getblast is working.
thank you.
