### ISSUE TITLE
format of model.rxnConfidenceScores

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#46]
Cobra specifies that model.rxnConfidenceScores should be a numeric array. This makes sense.

For Raven, `ravenCobraWrapper` converts this to a cell array (of doubles), while `checkModelStruct` suggest that model.rxnConfidenceScores should be an array of strings.

Is there an explicit reason why Raven specifies that rxnConfidenceScores should be a cell array? If so, should it then be numeric or strings? If no explicit reason, then follow Cobra specification.

**Comment by simas232** [comment]
It doesn't have an explicit reason. We can therefore follow COBRA specification for rxnConfidenceScores.

**Comment by Hao-Chalmers** [comment]
A number of functions need to be modified regarding this format change.

**Comment by edkerk** [comment]
Let's convert to numeric array, and close this issue when completed.

**Comment by simas232** [comment]
Fixed in 2053ffea2786cb2d6409dfeb55d95d3a13145f7a and 4a5e7f4d9027c114368676ba4f786a5bbabc167a.

**Comment by simas232** [comment]
This issue is solved already in devel branch and will be closed as soon as the it will be updated to master branch.

**Comment by edkerk** [comment]
This is now pushed to master: #89
