### ISSUE TITLE
Failed to make blastp executable

### ISSUE THREAD

**Issue by Sanrrone** [SysBioChalmers/RAVEN#460]
### Description of the issue:

After installation, cloning the repo or downloading the stable version (2.7.9) or trying addons from matlab, I cannot pass the first step that is check the installation. It seems the `which` function from matlab doesn't work as the Unix `which` command.
After run `checkInstallation` (from matlab addons installation at the end) I got:
```
>> checkInstallation

*** THE RAVEN TOOLBOX ***

 > Installing from location             /home/svalenzuela/Escritorio/RAVEN-2.7.9
 > Checking RAVEN release               2.7.9
   > Latest RAVEN release available     2.7.10
     Instructions on how to upgrade     <a href="https://github.com/SysBioChalmers/RAVEN/wiki/Installation#upgrade-to-latest-raven-release">here</a>
 > Checking MATLAB release              2022b
 > Checking system architecture         glnxa64
 > Set RAVEN in MATLAB path             Pass
 > Save MATLAB path                     Pass
   > Make binaries executable           Error using checkInstallation>makeBinaryExecutable
Failed to make blastp executable: chmod: no se puede acceder a '': No existe el archivo o el directorio
```
#### Reproducing this issue:

```matlab
checkInstallation
```
what should I do?
thanks in advance!

#### System information
1. RAVEN 2.7.9 stable.
2. Operating system (Ubuntu 22.04.1)
3. Matlab version: R2022b Update 3 (9.13.0.2126072)

**I hereby confirm that I have:**

- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by edkerk** [comment]
Does `runtests('blastPlusTests')` pass?

**Comment by Sanrrone** [comment]
yes, I got:
```
>> runtests('blastPlusTests')  
Running blastPlusTests
.
Done blastPlusTests
__________


ans = 

  TestResult with properties:

          Name: 'blastPlusTests/testBlastPlus'
        Passed: 1
        Failed: 0
    Incomplete: 0
      Duration: 12.5080
       Details: [1x1 struct]

Totals:
   1 Passed, 0 Failed, 0 Incomplete.
   12.508 seconds testing time.
```

**Comment by edkerk** [comment]
Ok, as workaround you can then comment out (with #), the following lines:

https://github.com/SysBioChalmers/RAVEN/blob/3a582aab41b9a7aab4602f5e7f95943e2b051074/installation/checkInstallation.m#L86-L94

I've also found a solution for the underlying problem, will make PR soon and implement in next RAVEN release.

**Comment by Sanrrone** [comment]
Now the installation is complete!, 
thanks you very much
