### ISSUE TITLE
export model in GitHub-ready formats

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#51]
Todo:

- [x] SBML format
- [x] MATLAB format
- [x] YAML format
- [x] COBRA-text format
- [x] combine all functionality in one function (`exportForGit.m`)
- [x] include versioning of toolboxes and packages
- [x] test functionality of exportForGit on existing GitHub-based models
- [x] document functionality in `exportForGit` function

Develop a function that automatically exports the model in formats that can directly be used to commit to GitHub following the SysBio-defined standards.

Exported formats are:

- .xml SBML L3V1 FBCv2
- .mat MATLAB structure
- .txt COBRA-style text format
- .yml YAML file

Futhermore include code from [saveYeastModel](https://github.com/SysBioChalmers/YeastMetabolicNetwork-GEM/blob/master/ComplementaryScripts/saveYeastModel.m) for versioning etc.

**Comment by edkerk** [comment]
Working on this on branch [feat/yaml_export](/SysBioChalmers/RAVEN/tree/feat/yaml_export).

**Comment by Hao-Chalmers** [comment]
What do you mean by "combined function" and "test function"?

**Comment by edkerk** [comment]
Combine everything in one function (e364d82ac1f899e2601da0f01aee92fb53672253) and test out its functionality. I'm working on this.

**Comment by Hao-Chalmers** [comment]
In `yaml_export` function, maybe it can just extract out information form the model itself, instead of relying on the libSBML (then avoid the issue of out of memory).

**Comment by edkerk** [comment]
That would mean extensive development to write that function, plus introduction of a non-standard file format.

**Comment by Hao-Chalmers** [comment]
There are pros and cons need to be balanced when choosing alternative approaches. Note that this yaml model format itself is non-standard.

**Comment by edkerk** [comment]
[YAML](http://yaml.org/) is a standardized file format, perhaps not extensively used for displaying genome-scale models.

However, the XML file is the ultimate format for model exchange (hence no support for YAML import). Diff of XML files is however messy. You can see YAML as a more readable and minimal representation of XML, so ideal to represent the changes in the XML file in YAML format.

**Comment by Hao-Chalmers** [comment]
Just try to suggest alternative ways in implementing export function for YAML format, which doesn't has to be restricted by existing XML format.
