### ISSUE TITLE
non-matching identifiers when running getModelFromHomology

### ISSUE THREAD

**Issue by glou123** [SysBioChalmers/RAVEN#549]
>> sedUnix('CDT1.faa');
>> modelaceto = importModel('RehMBEL1391_sbml_L3V1.xml');
modelaceto.mets = regexprep(modelaceto.mets, '\[[a-z]+\]$', '');
WARNING: The following metabolites are never used in a reaction:
	fol_c

WARNING: The following genes are not associated to a reaction:
	H16_B2371
	H16_A0184
	H16_B1757
	H16_A3290
	H16_A2106

>> modelaceto.id = 'aceto';
>> blast = getBlast('aceto1', ['CN.faa'], {'aceto'}, ...
{ 'CDT1.faa'});
BLASTing "aceto" against "aceto1"..
BLASTing "aceto1" against "aceto"..
>> {'aceto'}, 1, false, 10^-30, 150, 35);
 {'aceto'}, 1, false, 10^-30, 150, 35);
                                     ↑
Invalid expression. When calling a function or indexing a variable, use parentheses. Otherwise, check for mismatched delimiters.
 
>> model = getModelFromHomology({modelaceto}, blast, 'aceto1', ...
{'aceto'}, 1, false, 10^-30, 150, 35);
Error using getModelFromHomology (line 145)
Less than 5% of the genes in the template model with model.id "aceto"
can be found in the blastStructure. Ensure that the protein FASTA
used in getBlast and the template model used in getModelFromHomology
use the same style of gene identifiers

**Comment by edkerk** [comment]
From the warning message that is thrown when you load the model, we can see that a typical gene is formatted like “H16_B2371”. The `CN.faa` file that you use as input to `getBlast` uses some other style identifiers. This is why `getModelFromHomology` complains of non-matching of identifiers beteen the FASTA file and the template model.
