### ISSUE TITLE
support proteins field that match genes

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/RAVEN#558]
### Description of the issue:
COBRA has `protein` and `proteinNames` [fields](https://github.com/opencobra/cobratoolbox/blob/46b2dc7d3c92fb9ce0959a9bce0706b4d9e424f6/docs/source/notes/COBRAModelFields.md?plain=1#L29-L30) that match the `genes` field in size (which means that each gene can be associated to one protein). These are read from the SBML file from the `fbc_geneProduct.fbc_name` tag that is currently not considered by RAVEN. It would be convenient to support such a protein field as well.

`proteins` is an identifier field, which means that (if the field exists) it cannot be empty. COBRA solves this by filling it with `COBRAprotein1` etc. if no value was found in the SBML file. `proteinNames` has then the same content, but without filling empty entries with `COBRAprotein1` etc. As the `proteins` field is currently not used for anything (COBRA nor RAVEN), there is little reason to support this at the moment, while it is mostly redundant in comparison with `proteinNames`. Therefore, only the `proteinNames` field will be implemented. To ensure cross-compatibility, we will stick to the same field names.

**I hereby confirm that I have:**

- [x] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?q=is%3Aissue) or is already [discussed](https://github.com/SysBioChalmers/RAVEN/discussions).

**Comment by IVANDOMENZAIN** [comment]
In PR #559, functions `importModel` and `ravenCobraWrapper` return a MATLAB model structure that includes the field `proteinNames` as a row vector, however, all vector fields are column vectors in RAVEN. Should be corrected for consistency.

**Comment by IVANDOMENZAIN** [comment]
I've imported the same `.xml` model file, containing information stored in the SBML field `fbc:geneProduct.fbc:name`, using both `readCbModel` from the latest release, and also `importModel` in RAVEN (updated devel branch [04cdcc9](https://github.com/SysBioChalmers/RAVEN/commit/04cdcc92b803d32d206b197d3a5fc96584111f48)). COBRA returns a MATLAB structure with this information in the field `.proteins` and does not add `proteinNames`field. 
In contrast, RAVEN returns this information in the field `.proteinNames` and does not add `.proteins` field to the model structure. This discrepancy causes that, when an SBML model imported to MATLAB with COBRA is then transformed to RAVEN (using the `ravenCobraWrapper` function) this information gets lost.

**Comment by edkerk** [comment]
Thanks for reporting, then I misinterpreted [COBRA](https://github.com/opencobra/cobratoolbox/blob/106a6ca07d878879e3a023571aeca01314ee3df2/src/base/io/utilities/readSBML.m#L187-L198), I now see that they indeed never add the `.proteinNames` field to `model`. With this in mind, let's also use the `proteins` field in RAVEN. `ravenCobraWrapper` can then add/remove `COBRAProteinXXX` entries when converting model variants.

**Comment by IVANDOMENZAIN** [comment]
@edkerk I agree with the suggested approach, will fix as new PR.
