### ISSUE TITLE
Pre-trained Hidden Markov Models (HMMs) not available for download

### ISSUE THREAD

**Issue by silviamorins** [SysBioChalmers/RAVEN#59]
Hi,
the files containing the Pre-trained Hidden Markov Models (HMMs) are currently not available for download - do you know when it will be possible to have them again? In order to use them for a model reconstruction inside the Toolobox.

**Comment by edkerk** [comment]
I assume that you refer to the links in the README.md / Wiki.

HMMs are now automatically downloaded by the `getKEGGModelForOrganism` function, as detailed in the documentation `..\doc\external\kegg\getKEGGModelForOrganism.html`.

Please inform us if downloading using the `getKEGGModelForOrganism` function does not work.

Will update the README.md / Wiki to reflect this.

**Comment by edkerk** [comment]
Updated links in [Wiki](https://github.com/SysBioChalmers/RAVEN/wiki/HMMs) for manual downloading of HMMs.

**Comment by silviamorins** [comment]
I will try the function now.
I see the links are updated, thank you - however, they lead all to the download of euk100_kegg82.

**Comment by edkerk** [comment]
The links are updated and are now point to the correct files.

Are you sure you have write permission in your current working directory (run `pwd` to find out your current working directory). If not, then first browse to a directory that you know you have access rights (e.g. `My Documents`).

**Comment by silviamorins** [comment]
That helped. Thank you!
