### ISSUE TITLE
fix: deletion of genes in "multiple rules"

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/RAVEN#69]
**Description of the issue:**
After a short discussion in issue [#78](https://github.com/SysBioChalmers/YeastMetabolicNetwork-GEM/issues/78) of the yeast repo, I have been looking into how RAVEN handles gene deletions for complexes/isozymes/etc. The results are... well, not good:

- [x] When trying to use `removeGenes.m` to delete genes, the only ones that can be successfully deleted are genes in "single rules", i.e. only one gene in the `grRules` field. Any gene that is involved in a "multiple rule", e.g. `gene1 and gene2`, `gene1 or gene2`, etc. is not deleted by this function.
- [x] Furthermore, the output `reducedModel` looses about half the genes (probably the ones in those multiple rules, but I did not check).
- [x] Finally, `findGeneDeletions.m` does not call `removeGenes.m` (one would expect so to avoid redundant code), and has the major disadvantage that, as stated in the instructions of that function, it disregards complexes (`gene1 and gene2`) and assumes that any "and" is actually an "or". The latter is because it performs deletions by reading the `rxnGeneMat` field, which cannot distinguish between complexes and isozymes (it only has 1s and 0s).

The reader by now will have gathered that all of this is a huge issue when it comes to predicting KOs, and it should be fixed immediately.

**Case study:**
Loading the yeast model and testing `removeGenes.m` with a single rule (`r_0003 <- YAL060W`) and 2 multiple rules (`r_0005 <- YGR032W or YLR342W` and `r_0013 <- YEL038W and YMR009W`).
* **Expected output:**
Each time we use the function we should be able to remove the gene we want. Also, we should observe the following behaviors:
  * Delete `YAL060W` -> delete rxn `r_0003`
  * Delete isozyme `YGR032W` -> don't delete rxn `r_0005` (but change rule to only `YLR342W`)
  * Delete isozymes `YGR032W` & `YLR342W` -> delete rxn `r_0005`
  * Delete subunit `YEL038W` -> delete rxn `r_0013`

* **Obtained output in `devel`:**
The only deletion that actually works is the gene in the single rule (`YAL060W`), all other changes are skipped. The flag `removeRxnsWithComplexes` was tested both =true and =false, with no differences in the output.

* **Reproducing these results:**
All this analysis can be seen in the private repo [gem-scripts](https://github.com/SysBioChalmers/gem-scripts/blob/master/Ben/checkDeletions.m) or can be downloaded by anyone [here](https://github.com/SysBioChalmers/RAVEN/files/1855227/checkDeletions.zip).

**Proposed solution:**
With @IVANDOMENZAIN we came up with a fix to all of this: Decide if the reaction should be removed or not based on `grRules` and not `rxnGeneMat`. We have written a quite concise function for that, that works as long as the `grRules` are properly formatted. In order to check that, we also have another function. However before we continue the work and make a PR that fixes all of this issue, we would like impressions and/or recommendations from the community :) Maybe my case study is incomplete, or the functions actually work sometimes with different input?

Please give here any feedback on this major issue, to solve it ASAP

**Comment by simas232** [comment]
Did you try to `expandModel` before removing genes?

**Comment by edkerk** [comment]
Thanks for the thorough review of the functionality in both RAVEN and COBRA. I fully agree that this is a major issues, also as knockout predictions are often used as statistic for model quality.

Using `grRules` seems like the only reasonable approach. These should be in a correct formatting, no matter what, so a separate function for this is a good idea. Regarding your case study, make sure you also include nested `grRules`, with multiple AND and OR relationships:

**Example: `(GeneA and GeneB) or (GeneC and GeneB)`**
* Is there a preference over this format, or the alternative `(GeneA or GeneC) and GeneB` ?
* Can the new approach deal with these situations?
* Ideally, can it deal with double-knockouts? Removing GeneA _and_ GeneC should remove the reaction.

**Comment by BenjaSanchez** [comment]
@simas232 I did not try `expandModel.m`, I suppose some of these issues will be fixed with that one as it simplifies the rules by adding new reactions (can it do it for any kind of rule?); however I think it's non-ideal to increase the size of the model excessively when we can just have a good parser that reads complicated rules, specially considering that many users use the "KO-model" for further simulations.

@edkerk it will also handle well nested rules, like the one you mention. The way the rule is written (`(GeneA and GeneB) or (GeneC and GeneB)` - `(GeneA or GeneC) and GeneB`) will not matter, as the function (spoiler alert) replaces gene names with logicals and then evaluates the expression to decide to block or not. Double/triple/n-tuple knockouts will also work as the function will receive as input an array of genes.

**Comment by Hao-Chalmers** [comment]
RAVEN has been disregarding 'enzyme complex' since the very begining (probably due to the lack of this information from KEGG), this led to the only consideration of **`and`** relation in grRule and rxnGeneMat generation by treating everything as isoenzymes. We may work toward a total solution from this case, with thorough discussion.

Regarding the improving of knockout prediction, a detail survey of relevant COBRA functions would be beneficial. And the `grRules` should be relied on.

**Comment by simas232** [comment]
@BenjaSanchez, using `expandModel` before removing genes should fix the first issue you pointed in the first entry here.

**Comment by Hao-Chalmers** [comment]
A well formatted **`grRule`** might be the key to proper/efficient parse. Knockout prediction may only aim to resolve grRules as such: **(GeneA and GeneB) or (GeneC and GeneB)**. And all relevant RAVEN functions could be modified to align with this format.

An addition reformatting function can then be developed for reformatting cases from **`(GeneA or GeneC) and GeneB)`** to **`(GeneA and GeneB) or (GeneC and GeneB)`**.

**Comment by IVANDOMENZAIN** [comment]
@Hao-Chalmers, we already thought about that and have developed a simple function for the standardization of grRules  that can be previously run and make them suitable for the parsing process.

**Comment by BenjaSanchez** [comment]
@simas232 yes, but that would require the user knowing in advance that he/she should apply that function. By properly parsing rules, expanding the model will not be necessary, thus avoiding models growing excessively in size.

@Hao-Chalmers regarding the rule format, the parsing will be done efficiently for any format, as long as the rule is consistent, as it will be based on converting the text rule to a logical rule. Regarding COBRA, once we fix it here my plan is to start an issue in COBRA as well, referencing the (by then) integrated new functions in RAVEN.

**Comment by simas232** [comment]
@BenjaSanchez, it depends what ideas do you guys have for rules parsing. My advise would be just to modify `removeGenes` in the following way:
1. Save _model.rxns_ and _model.rxnNames_ rxns as backup cell arrays.
2. Run `expandModel` in very beginning of `removeGenes`. 
3. Run `contractModel` in the very end of `removeGenes`. This function does exactly the opposite than `expandModel`.
4. Restore the reaction ids and names from backup cell arrays, as these may become different after using `contractModel`.

The limitation of this suggestion is that you may want to have reactions separate even though the equation is the same. For example, some GEMs have gene associated ATP hydrolysis reaction and this reaction is usually kept separate from ATPM reaction. Running contractModel would falsively stack these reactions. This would also introduce the disrepancy of the rxns number of the raw model and modified model. So text mining may be helpful here, maybe involving regexes.

**Comment by BenjaSanchez** [comment]
@simas232 I'm pretty sure that just making a good parser (that btw we already have written)  will be both 1) simpler to understand and 2) more efficient, as adding rxns to later remove them will take a while (which can become an important factor in let's say a double-deletion study). What we can do later is to test which solution is faster? :)

**Comment by simas232** [comment]
@BenjaSanchez, I see your point. You can go ahead with this implementation, just make sure that your implementation does no break functionality of `getModelFromHomology`. This is the only RAVEN function, which calls `removeGenes`.

**Comment by simas232** [comment]
@BenjaSanchez, did you check whether the issues you pointed here are also relevant for RAVEN structure, obtained when importing SBML file with `importModel`? If so, we need to implement `standardizeGeneRules` not only in `ravenCobraWrapper`, but also in other RAVEN input functions.

**Comment by BenjaSanchez** [comment]
@simas232 yes, we intend to include `standardizeGeneRules` at the beginning of `removeGenes` as well, but to make it optional with a flag, as we want to skip it in single/double/etc deletion studies and only do it once at the beginning for speed. The function could also have use in other sections of RAVEN I suppose, especially when a decision based on `geneRxnMatrix` is taken. Any functions like that?

**Comment by Hao-Chalmers** [comment]
Would be good to include/reuse `standardizeGeneRules` into `getRxnGeneMat`.

**Comment by simas232** [comment]
The idea would be to implement these standarized gene rules as RAVEN standard thereby ensuring that grRules with additional brackets does not exist. That is, all the RAVEN functions which generate RAVEN structure (`importModel`, `importExcelModel`, `ravenCobraWrapper`, `getModelFromHomology`, `getKEGGModelForOrganism`, `getMetaCycModelForOrganism`) would need have `standardizeGeneRules` implementation. In the end, only the people already having RAVEN structure as mat file would be left behind, but would always have an ability to run `removeGenes`.

**Comment by Hao-Chalmers** [comment]
@simas232 regarding the existing (left behind) mat files, they can be updated by `standardizeGrRules`.

**Comment by tpfau** [comment]
>  Finally, findGeneDeletions.m does not call removeGenes.m (one would expect so to avoid redundant code), and has the major disadvantage that, as stated in the instructions of that function, it disregards complexes (gene1 and gene2) and assumes that any "and" is actually an "or". The latter is a problem that is also prevalent in COBRA toolbox (function deleteModelGenes.m), and its because both toolboxes perform deletions by reading the rxnGeneMat field, which cannot distinguish between complexes and isozymes (it only has 1s and 0s).

From a COBRA Toolbox point of view:
This is not correct. While the COBRA toolbox does use `rxnGeneMat` in this function, it only does so in order to select which reactions could be influenced by the deletion.
And it will set all reactions to 0 which according to their GPR rule will no longer be able to carry flux (i.e. which don't have any remaining isozyme to catalyse them). 

But I agree, that `deleteModelGenes` is not great, and I'm wondering, whether a gene which is deleted in a model should still be in the model or whether we should remove it alltogether (along with any reaction that cannot carry flux any more...)
Whats your opinion here?

**Comment by BenjaSanchez** [comment]
@tpfau yes you are correct, I was too quick in my assessment but `deleteModelGenes` does indeed distinguish complexes from isozymes. What it does not do is to modify the corresponding rule to leave it without the gene that was deleted, and also as you state it leaves the gene still in the model.

To me what makes more sense is to give the user the choice: See PR #73 in which we included a flag so that the user can choose if he/she prefers to leave the corresponding reactions blocked or instead delete them. Furthermore, if they are chosen to be blocked, the gene rule is adapted to take out the deleted gene/complex. This also applies to any reaction that is still allowed to carry flux but had the deleted gene as a possible isozyme. The main advantage of doing this would be that if one wishes to perform further analysis with the KO model, the model is completely adapted to do so.

**Comment by tpfau** [comment]
@BenjaSanchez I absolutely agree, as long as you have complete knockouts.
The main issue comes, when performing only partial knockouts and continued usage of the model. 
Essentially, what we would need is a "efficiency" vector for the genes in the model and some "originalBounds" stats. Otherwise a double knockdowns can become problematic.

**Comment by edkerk** [comment]
It is discussed in commit 8d6a909b8712c71aa1721960663d8c7450992519 that the `standardizeGrRules` function should first be run stand-alone on a 'new' model, and if potential problematic `) and (` relationships are found, it should provide more detailed information on how the model should be curated.

When `standardizeGrRules` is invoked from other functions, it should either be silent, or only give a 1-line message if potential problematic  `) and (` relationships are found.

The `getModelFromHomology` pipeline is likely to make nested and/or relationships: 

- Let's say the template model has `G1 and G2` as grRule
- BLAST indicates that genes H1 and H2 from the _new_ organism are homologous to G1, and H3 and H4 are homologous to G2.
- The grRule for the new model will then read `(H1 or H2) and (H3 and H4)`.

At the end of `getModelFromHomology`, it should give detailed output on what grRules should be manually curated.

**Comment by edkerk** [comment]
@BenjaSanchez 
The last remaining task is to amend `findGeneDeletions` to use `removeGenes`. Do you have any suggestions for this? It seems that a significant part of the `findGeneDeletions` function is about avoiding enzyme complexes, which can be left out, and commands like `tempModel=setParam(model,'eq',model.rxns(I),0);` can be replaced with `removeGenes`-functionality instead?

**Comment by IVANDOMENZAIN** [comment]
@edkerk 
You're right, as it uses the field `rxnGeneMat` for getting the genes that should de deleted, based on their associations with reactions, complexes are never considered properly.  

The function `removeGenes` should substitute the usage of `setParam` that is fed by indexes gotten from `rxnGeneMat`, the new function will perform the whole task in a better way. However, we need to find the proper strategy for reducing the problem size for double knockouts, the current algorithm does it, but dissregarding complexes.

**Comment by edkerk** [comment]
I've made a first implementation of this in 0fc099f7dc54127391d03f8efb6d91f8e2d09b4b, should be further tested.

**Comment by edkerk** [comment]
I'd like to revisit the need for `standardizeGrRules` function:

### Can potential problematic grRules not just be left alone?

[FYI, this function has also been discussed in #73]

Now that `standardizeGrRules` is an integral part of various functions including `importModel`, models are changed when going through their first RAVEN I/O-cycle. While simple `grRules` are fixed through this cycle, problematic grRules are possibly/likely irrevocably invalidated.

As example, the following grRule from a model:

`SCO4564 and SCO4566 and SCO4568 and (SCO4562 or SCO4599) and (SCO4563 or SCO4600) and (SCO3392 or SCO4565) and (SCO4567 or SCO6560) and (SCO4569 or SCO4602) and (SCO4570 or SCO4603) and (SCO4571 or SCO4604) and (SCO4572 or SCO4605) and (SCO4573 or SCO4606 or SCO6954) and (SCO4574 or SCO4607) and (SCO4575 or SCO4608)`

is irrevocably changed into the following grRule when loading the model with `importModel` (note the 4th and 5th gene and compare with above):

`(SCO4564 and SCO4566 and SCO4568 and (SCO4562) or (SCO4599) and (SCO4563) or (SCO4600) and (SCO3392) or (SCO4565) and (SCO4567) or (SCO6560) and (SCO4569) or (SCO4602) and (SCO4570) or (SCO4603) and (SCO4571) or (SCO4604) and (SCO4572) or (SCO4605) and (SCO4573) or (SCO4606) or (SCO6954) and (SCO4574) or (SCO4607) and (SCO4575) or (SCO4608))`

A warning is given that this is a potential problematic grRule, but fixing this would result in 3000 combinations. Is it absolutely necessary to enforce the standardized grRules?

The main purpose of `standardizeGrRules` is to make the model work with `removeGenes`. But what would be problematic grRules?

1. If grRule has unbalanced brackets --> `canCarryFlux` will throw an error when attempting to evaluate the "logical grRule".
2. If nested and/or relationships are incorrect --> `canCarryFlux` can still work perfectly fine, but this is where a warning could be thrown that results might be unreliable.

@IVANDOMENZAIN @BenjaSanchez , could you comment on when else are there potential problematic grRules? Isn't it better to throw warnings about nested grRules in `removeGenes`, while grRules can be imported _as is_ from the SBML file?

Note that cobra [specifies](https://github.com/opencobra/cobratoolbox/blob/master/src/base/parseGPR.m) this as an example grRule:

`% 3. The general format of a GPR is: Gene1 or Gene2 and (Gene3 or Gene4)`

This would not survive a RAVEN I/O-cycle.

**Comment by BenjaSanchez** [comment]
@edkerk reg `removeGenes`:
* The sub-function `canRxnCarryFlux` will work as long as the grRule is a valid logical statement. That means that there will always be a correct decision of whether the reaction should be blocked or not, for any of the examples that you mention.
* The sub-function that will **not** always work is `removeGeneFromRule`, which requires the rule to be in the format `(A and B) or (C and D)`; otherwise it's too complicated to adapt. Also, as pointed out by @IVANDOMENZAIN [previously](https://github.com/SysBioChalmers/RAVEN/commit/00f7f9698f4461778d13133ac6ad5e793974ce94), these are not super common scenarios, so it's easier than the user first fixes them and then proceeds with the analysis.
* Overall then, in terms of predicting KOs `removeGenes` will give proper results if a model has non-standard `grRules`, bot might give errors if further analysis is done with the resulting KO models.

reg `standardizeGrRules`:

> Can potential problematic grRules not just be left alone?

They are indeed left alone by `standardizeGrRules`. Whatever can be fixed by that function (unbalanced parenthesis for instance) is fixed, but when the function cannot solve it due to non-standard ways of writing the rule (as the one you mention), the rule is kept the same.

> As example, the following grRule from a model [...]:

Which grRule is that one? we could not find it in `Sco4` to test.

> [...] This would not survive a RAVEN I/O-cycle.

We tried an I/O cycle with `Sco4` and indeed some grRules change, but it is not because of `standardizeGrRules`. We tested this by repeating the I/O cycle but with `standardizeGrRules` muted in `importModel`, and we got the same results ([here](https://github.com/SysBioChalmers/RAVEN/files/1971070/testIOcycle.zip) is the script we used). So a separate issue should be created to address this problem. @simas232 which other functions modify `grRules`? We noticed in lines 830-868 of `importModel` that additional changes to `grRules` are made prior to `standardizeGrRules`, and we think that this might be the problem.

**Comment by edkerk** [comment]
@BenjaSanchez @IVANDOMENZAIN 
Thanks for testing this and the clear explanation. Note that your `testIOcycle.m` should be run on the `devel` branch of Sco4, as there has been some manual curation of grRules already. Nonetheless, commenting out line 866 in `importModel` indicates that it is not standardizeGrRules that screws up the grRules.

It indeed turns out that line 837-839 of `importModel` are problematic. These were inherited from RAVEN 1.0, so it is unclear to me what is exactly the point of these precise lines. As `standardizeGrRules` now already fixes most grRules and prompts the user to manually curate the potential problematic grRules, it seems fine to discard line 830-849. Will do this in a fix-branch. @simas232 any alternative thoughts?

**Comment by IVANDOMENZAIN** [comment]
You're right, we just write this test for visualizing the changes that were done on the problematic grRules by `importModel`.

Lines 837-839  make sure that every isoenzyme is enclosed into brackets, however it doesn't take care of the problematic cases and these will also be modified prior to the standardization step in line 865. So, this is one of the main reasons of why the final results in the field `grRules` differ after a whole cycle of import/export model. 

As you said, lines 830-849 and also 871-873 should be discarded and also add line 834 to `standardizeGrRules`.

I've already created the branch. Let me know if you find something else. @edkerk, @BenjaSanchez, @simas232

**Comment by edkerk** [comment]
All issues are now fixed in #98, will close when pushed to master.
