### ISSUE TITLE
Static addition of POI to java class path

### ISSUE THREAD

**Issue by tpfau** [SysBioChalmers/RAVEN#75]
Coming from #55 I just wanted to test this on my machine and noticed, that RAVEN adds a static java class path file. 
Personally, I think it would be better if this is not done in a static way (the user might move the RAVEN directory, he might want to use a different poi lib etc pp). If you want this to happen by default, you could create a startup.m in the RAVEN main directory that adds the librarys dynamically at startup if the toolbox is on the path or call it in checkInstallation.
This would also avoid the forced matlab restart during setup.

**Comment by Hao-Chalmers** [comment]
Good comments in improving robustness by adding relative (internal) path, other external libs (e.g. libSBML) may also be treated like this (with increased toolbox size though, but convenient for end users).

**Comment by edkerk** [comment]
Could also write a function that checks whether paths are already added or not. If not, then dynamically (?, is that the opposite of static java class path files?) add the POI files.

This function can then be called in the beginning of relevant I/O functions.

Not sure about all other external libs, probably better to keep this in the checkInstallation, as this also ensures that all RAVEN toolbox subfolders are in the Matlab path?

One issues I've been running into is when users do not have admin rights (or at least _enough_ rights), then there can be issues with adding folders and files to path files. Would this also circumvent that?

**Comment by tpfau** [comment]
using `javaaddpath` does not require any specific rights/permissions.  
This is something specific for the POI libraries (or any java librariers that are used).

**Comment by edkerk** [comment]
This is now pushed to master: #89
