### ISSUE TITLE
Bug:ravenCobraWrapper doesn't create same amount of metMiriams/rxnMiriams with mets/rxns

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/RAVEN#99]
I use ravenCobraWrapper to convert a cobra model to raven format, it create less amount of metMiriams/rxnMiriams compared to mets/rxns. As below, you can see I have 2224 mets, but only have 2220 metMiriams.

model= 

  struct with fields:

                   rxns: {3496×1 cell}
                   mets: {2224×1 cell}
                      S: [2224×3496 double]
                     lb: [3496×1 double]
                     ub: [3496×1 double]
                    rev: [3496×1 double]
                      c: [3496×1 double]
                      b: [2224×1 double]
                  comps: {14×1 cell}
              compNames: {14×1 cell}
               rxnNames: {3496×1 cell}
                grRules: {3496×1 cell}
             rxnGeneMat: [3496×909 double]
             subSystems: {3496×1 cell}
                eccodes: {3496×1 cell}
             rxnMiriams: {2985×1 cell}
               rxnNotes: {3496×1 cell}
    rxnConfidenceScores: {3496×1 cell}
                  genes: {909×1 cell}
         geneShortNames: {909×1 cell}
               metNames: {2224×1 cell}
               metComps: [2224×1 double]
            metFormulas: {2224×1 cell}
             metMiriams: {2220×1 cell}
             metCharges: [2224×1 double]

**Comment by edkerk** [comment]
@feiranl thanks for reporting this, could you please upload/send the model that showed this behaviour?

**Comment by BenjaSanchez** [comment]
@edkerk @feiranl using yeast-GEM from `devel` + RAVEN in `devel` I actually don't observe this behavior. Could it be an out of date version of the model @feiranl?

**Comment by feiranl** [comment]
I am not sure, but now it is okay. It can generate equal amount of rxnMiriams/metMiriams with rxns/mets.
